#!/usr/bin/env bash
# The V2 mutant round. Each mutation must redden ITS OWN leg and leave the others alone — and for each one, the
# question asked before it was written was "can this mutant MOVE the leg's own reference?". Where it could, the
# reference was moved out of its reach first (m1's bound comes from a separate control run; m2's fractions come
# from a restored runtime, not from the mutated arbiter).
#
# ⛔ RESTORED FROM A COPY, NEVER FROM GIT — a harness that restores with `git checkout` restores over uncommitted
# work. The copy is taken first, the tree is restored after every run, and the script refuses to start on a dirty
# tree, because a dirty tree is the case where the copy is the only thing between the mutation and the work.
#
# ⛔ DO NOT EDIT THIS FILE WHILE IT IS RUNNING. Bash reads a script incrementally, by byte offset: an edit made
# mid-run shifts everything after the read point and the shell resumes mid-word. MEASURED on the V1 round —
# `line 46: azy-guard-removed: command not found`, and a mutant silently skipped.
#
#   bash tools/harness/mutants-v2.sh <out-dir> [name-filter]
set -uo pipefail
cd "$(dirname "$0")/../.."
OUT="${1:?usage: mutants-v2.sh <out-dir> [name-filter]}"
ONLY="${2:-}"
mkdir -p "$OUT"
if [ -n "$(git status --porcelain)" ]; then echo "REFUSING: the tree is dirty. Commit first — a mutant round restores over whatever is here."; exit 1; fi
AUTO=loader/tmt-auto.js
cp "$AUTO" "$OUT/tmt-auto.js.orig"
restore() { cp "$OUT/tmt-auto.js.orig" "$AUTO"; }
trap restore EXIT

mutant() {
  local name="$1" mut="$2"; shift 2
  if [ -n "$ONLY" ] && [[ "$name" != *"$ONLY"* ]]; then return 0; fi
  restore
  python3 -c "$mut" || { echo "$name: THE MUTATION DID NOT APPLY"; return 1; }
  echo "=== $name ==="
  git --no-pager diff --stat -- "$AUTO"
  "$@" > "$OUT/$name.log" 2>&1
  echo "$name: exit $? — $(grep -cE '^RED' "$OUT/$name.log") RED row(s), $(grep -cE '^GREEN' "$OUT/$name.log") green"
  grep -E '^RED' "$OUT/$name.log" | cut -c1-260
  restore
  git --no-pager diff --stat -- "$AUTO" | grep . && echo "!! NOT RESTORED" || echo "restored: diff is empty"
}

V2="node tools/harness/gates-v2.mjs --no-summary"

# ---- the stall fallback ------------------------------------------------------------------------------------------
# ⛔ m1 IS THE ONE THE BRIEF NAMES. Its leg's reference is a SEPARATE control run with K so large the fallback can
# never fire, so the intervals it is compared against are purely own-rule and this mutation cannot reach them.
mutant m1-fallback-reset-feeds-typical \
  "p='$AUTO';s=open(p).read();o='if (P && P.modifier && !d.fallback && before !== undefined)';assert o in s;s=s.replace(o,'if (P && P.modifier && before !== undefined)');open(p,'w').write(s)" \
  $V2 --part 1

# The ARBITER, reversed. "One per tick" and "neither is starved" both survive this, which is why the leg pins WHICH
# of two constructed stalled features fires.
mutant m2-arbiter-takes-the-lowest-fraction \
  "p='$AUTO';s=open(p).read();o='if (best === null || c.progress > best.progress) best = c;';assert o in s;s=s.replace(o,'if (best === null || c.progress < best.progress) best = c;');open(p,'w').write(s)" \
  $V2 --part 1

# ---- rate-peak's two parameters ----------------------------------------------------------------------------------
mutant m3-value-buffer-ignored \
  "p='$AUTO';s=open(p).read();o='var need = best.times(1 - buf);';assert o in s;s=s.replace(o,'var need = best.times(1);');open(p,'w').write(s)" \
  $V2 --part 1

mutant m4-hold-clock-never-clears \
  "p='$AUTO';s=open(p).read();o=\"if (!over) { delete rateHold[f.id]; return\";assert o in s;s=s.replace(o,\"if (!over) { return\");open(p,'w').write(s)" \
  $V2 --part 1

# ---- a refused edit ------------------------------------------------------------------------------------------------
# ⚠ AIMED AT THE GUARD, NOT AT THE MESSAGE. The first cut bypassed `setSavedParam`'s `checkParam` and came back
# GREEN — correctly: the value is then formatted into `gain>=bananax` and handed to `setSavedPolicy`, whose
# `policyOk` refuses it, so nothing is written and `ok` is still false. `checkParam` buys the sentence the player
# reads; the GUARD is one layer down, and that is what a mutant has to remove for the leg to mean anything.
mutant m5-refused-value-reaches-the-save \
  "p='$AUTO';s=open(p).read();o='    if (typeof policy !== \'string\' || !policyOk(f.kind, policy)) return { ok: false, policy: policyOf(f), error:';assert o in s;s=s.replace(o,'    if (false) return { ok: false, policy: policyOf(f), error:');open(p,'w').write(s)" \
  $V2 --part 1

# ---- the memory really is in runtimeState --------------------------------------------------------------------------
# "the clock lives in a closure only": the state is still kept, it just never leaves the process. Everything except a
# RESUME is unmoved, which is exactly what part 3's cut-and-resume arm exists to see.
mutant m6-stall-memory-not-in-runtimestate \
  "p='$AUTO';s=open(p).read();o='    if (ns) o.stallIntervals = sm;';assert o in s;s=s.replace(o,'    if (false) o.stallIntervals = sm;');o2='    if (nss) o.stallSince = ss;';assert o2 in s;s=s.replace(o2,'    if (false) o.stallSince = ss;');o3='    if (nh) o.rateHold = rh;';assert o3 in s;s=s.replace(o3,'    if (false) o.rateHold = rh;');open(p,'w').write(s)" \
  $V2 --part 3

# ---- the editors -----------------------------------------------------------------------------------------------------
# ⛔ THE ONE THE BRIEF NAMES: the picker writes the save and the DECISION PATH goes on reading the table. The label
# still changes — `explain()` reports the getter — so only the ACTION-COUNT row can see it.
mutant m7-decision-path-ignores-the-save \
  "p='$AUTO';s=open(p).read();o='    var s = policyOf(f);\n    if (f.policyStr !== s)';assert o in s;s=s.replace(o,'    var s = f.policy0;\n    if (f.policyStr !== s)');open(p,'w').write(s)" \
  $V2 --part 4

# The HOTKEY guard removed: typing into a field reaches the game's own document handler.
mutant m8-hotkey-guard-removed \
  "p='$AUTO';s=open(p).read();o=\" @keydown.stop=\\\"onKey\\\" @keyup.stop @keypress.stop>'\";assert o in s;s=s.replace(o,\" @keydown=\\\"onKey\\\">'\");open(p,'w').write(s)" \
  $V2 --part 4

# ---- the save key ------------------------------------------------------------------------------------------------
# `edits` out of `startData` is U6's bug in its V2 shape: Vue 2 cannot observe a key added after creation.
mutant m9-edits-unseeded \
  "p='$AUTO';s=open(p).read();o=', armLocked: false, edits: {} };';assert o in s;s=s.replace(o,', armLocked: false };');open(p,'w').write(s)" \
  $V2 --part 5
