#!/usr/bin/env bash
# The U11 mutant round (docs/mobile.md, "A layer never opened" and "The reset glow"). Each mutation breaks exactly
# ONE claim and must redden the check that exists for it — by NAME, out of gate M1's own JSON row — while leaving
# the others alone.
#
# ⛔ RESTORED FROM A COPY, NEVER FROM GIT (the U9 round's rule: a harness that restores with `git checkout`
# restores over uncommitted work). The copies are taken first and the script refuses to start on a dirty tree.
# ⚠ `-uno`: in a WORKTREE `node_modules` is a SYMLINK and `.gitignore`'s `node_modules/` does not match one.
#
# ⛔ DO NOT EDIT THIS FILE WHILE IT IS RUNNING: bash reads a script by byte offset.
#
#   bash tools/harness/mutants-u11.sh <out-dir> [name-filter]
#
# ⚠ THE GAMES ARE PER MUTANT, taken from its own expectation list:
#   · `ptr`              — the item-1 witness: one of the three engines whose `updateTempData` skips `unlocked`
#                          for a closed tab (16 stale at the fresh save, 54 at the deepest snapshot), and one of
#                          the 79 games the brief's census names. Also a glow witness on the POINTS fallback, since
#                          its engine keeps no `resetTime`.
#   · `the-burning-tree` — the item-1 CONTROL: all 14 of its buyables default `unlocked`, and its engine evaluates
#                          every `unlocked` on every tick anyway, so the leg is vacuous there by construction.
#   · `the-yes-tree`     — the glow witness on the `resetTime` signal (ptr and the-burning-tree both take the
#                          points fallback), and a counter-glow witness.
# ⚠ A leg that ABSTAINS reads as GREEN here, and the row prints each verdict so an abstention is visible.
set -uo pipefail
cd "$(dirname "$0")/../.."
OUT="${1:?usage: mutants-u11.sh <out-dir> [name-filter]}"
ONLY="${2:-}"
mkdir -p "$OUT"
if [ -n "$(git status --porcelain -uno)" ]; then echo "REFUSING: tracked files are modified. Commit first — a mutant round restores over whatever is here."; exit 1; fi
FILES="loader/layerlist.js loader/layerlist.css"
for f in $FILES; do cp "$f" "$OUT/$(basename "$f").orig"; done
restore() { for f in $FILES; do cp "$OUT/$(basename "$f").orig" "$f"; done; }
trap restore EXIT

LEGS="never glow rmotion counter"

read_row() {
  node tools/harness/page.mjs "$1" --gate mobile 2>/dev/null | node -e '
    let s = ""; process.stdin.on("data", (d) => { s += d; });
    process.stdin.on("end", () => {
      const line = s.split("\n").filter((l) => l.startsWith("{")).pop();
      if (!line) { console.log("PARSE=false"); return; }
      const d = JSON.parse(line);
      const bad = (v) => /^READING|^THE CHIPS/.test(String(v && v.verdict));
      const gbad = (v) => /^THE |^STILL|^IT /.test(String(v && v.verdict));
      const o = { never: !bad(d.neverOpened) && !bad(d.neverOpenedFresh), glow: !gbad(d.glow), rmotion: !gbad(d.glowReduced), counter: !/^THE |^A COUNTER/.test(String(d.counterGlow && d.counterGlow.verdict)) };
      console.log(Object.entries(o).map(([k, v]) => `${k}=${v === true}`).join(" ")
        + ` || fresh: ${d.neverOpenedFresh && d.neverOpenedFresh.verdict} || snapshot: ${d.neverOpened && d.neverOpened.verdict}`
        + ` || glow: ${d.glow && d.glow.verdict} || reduced: ${d.glowReduced && d.glowReduced.verdict} || counter: ${d.counterGlow && d.counterGlow.verdict}`);
    });'
}

# $1 = name, $2 = python mutation, $3.. = one `<game>=<leg>,<leg>` per game (an empty list is spelled `<game>=`).
mutant() {
  local name="$1" mut="$2"; shift 2
  local spec=("$@")
  if [ -n "$ONLY" ] && [[ "$name" != *"$ONLY"* ]]; then return 0; fi
  restore
  python3 -c "$mut" || { echo "$name: THE MUTATION DID NOT APPLY"; return 1; }
  echo "=== $name  (expects: ${spec[*]:-nothing red})"
  git --no-pager diff --stat -- $FILES | tail -1
  local ok=1
  for e in "${spec[@]}"; do
    local g="${e%%=*}" want="${e#*=}"
    want="${want//,/ }"
    local out; out="$(read_row "$g")"
    echo "  $g: $out" | tee -a "$OUT/$name.log"
    local red=()
    for leg in $LEGS; do grep -q -- "$leg=true" <<<"$out" || red+=("$leg"); done
    local got="${red[*]:-}"
    if [ "$got" = "$want" ]; then echo "  OK   $g — red: [${got:-none}]"
    else echo "  FAIL $g — red: [${got:-none}], expected [${want:-none}]"; ok=0; fi
  done
  [ "$ok" = 1 ] && echo "  => $name OK" || echo "  => $name FAILED"
  restore
  git --no-pager diff --stat -- $FILES | grep . && echo "!! NOT RESTORED" || echo "  restored: diff is empty"
}

echo "control (no mutant):"
mutant control "pass" ptr= the-burning-tree= the-yes-tree=

# ---- item 1: a layer never opened -------------------------------------------------------------------------------
# (1) THE FIX REVERTED — the list reads `tmp` alone again. ⛔ It must redden `ptr` (an engine that skips a closed
#     tab's `unlocked`) and LEAVE `the-burning-tree` GREEN (every buyable defaults, and its engine re-evaluates).
mutant m1-unlocked-from-tmp-only \
  "p='loader/layerlist.js';s=open(p).read();o='    if (kind === \'upgrades\' || !engineSkipsUnlocked()) return fromTmp();';assert o in s;s=s.replace(o,'    return fromTmp();');open(p,'w').write(s)" \
  ptr=never the-burning-tree=

# (2) the skip DERIVATION broken (it never recognises the engine) — the same defect one layer down, caught by the
#     same leg, which is what says the leg is about the engine's rule and not about our regex.
mutant m2-skip-never-derived \
  "p='loader/layerlist.js';s=open(p).read();o='player\\\\.tab\\\\s*!=+\\\\s*layer';assert o in s, o;s=s.replace(o,'player\\\\.tab\\\\s*<>\\\\s*layer');open(p,'w').write(s)" \
  ptr=never the-burning-tree=

# ---- item 2: the reset glow -------------------------------------------------------------------------------------
# (3) THE RETRIGGER GUARD REMOVED — the detector fires on a LEVEL (the signal is at or below its last reading)
#     instead of an EDGE. On a paused page the signal then holds still after the reset and every sample restarts
#     the animation: the failure is a glow that NEVER ENDS (or one lit with nothing having happened), not a
#     missing one. Reddens the motion leg on BOTH signals; the reduced-motion leg counts starts too, so it reddens.
mutant m3-glow-on-a-level-not-an-edge \
  "p='loader/layerlist.js';s=open(p).read();o='(was.t !== undefined && now.t < was.t) : (was.z === false && now.z === true)';assert o in s;s=s.replace(o,'(was.t !== undefined && now.t <= was.t) : (now.z === true)');open(p,'w').write(s)" \
  ptr=glow,rmotion the-yes-tree=glow,rmotion

# (4) prefers-reduced-motion IGNORED — the media block gone. Only the reduced-motion leg can see it.
mutant m4-reduced-motion-ignored \
  "p='loader/layerlist.css';s=open(p).read();o='@media (prefers-reduced-motion: reduce) {';assert o in s;s=s.replace(o,'@media (prefers-reduced-motion: no-such-value) {');open(p,'w').write(s)" \
  ptr=rmotion the-yes-tree=rmotion

# (5) THE GLOW NEVER STARTS — the event is detected and dropped. Both glow legs, since both count the start.
mutant m5-glow-never-starts \
  "p='loader/layerlist.js';s=open(p).read();o='    if (fired) glow(rec);';assert o in s;s=s.replace(o,'');open(p,'w').write(s)" \
  ptr=glow,rmotion the-yes-tree=glow,rmotion

# (6) THE COUNTER'S GUARD REMOVED — "rose" becomes "did not fall", a LEVEL again. Every counter then restarts on
#     every sample, with nothing bought: the counter leg's quiet window catches it before any construction.
mutant m6-counter-glow-on-a-level \
  "p='loader/layerlist.js';s=open(p).read();o='b > Number(a) : (b && typeof b.gt === \'function\' ? !!b.gt(a) : false)';assert o in s;s=s.replace(o,'b >= Number(a) : (b && typeof b.gte === \'function\' ? !!b.gte(a) : false)');open(p,'w').write(s)" \
  ptr=counter the-yes-tree=counter

# (7) THE RETRIGGER GUARD REMOVED, literally — the detector is still an edge, but once a card has fired it
#     RESTARTS the animation on every later sample. ⚠ m3 cannot stand in for this: a level detector dies at the
#     leg's QUIET window ("glowed with no reset") before the 1 s check is reached (a mutant with two effects dies
#     at the first check). This one is quiet until the event, so the ONLY check that can see it is
#     "still glowing after 1 s" — which is the check the brief asked to be proven.
#     ⚠ IT REDDENS `rmotion` TOO, and that is the mutant being right, not loose: the reduced-motion leg runs SECOND
#     on the same page, and the card the first leg lit is still restarting on every sample — so the second leg's
#     own quiet window sees it. Measured: motion "STILL GLOWING after 1 s — 6 starts for one reset", reduced
#     "IT GLOWED WITH NO RESET (2 start(s))".
mutant m7-retrigger-every-sample-after-an-event \
  "p='loader/layerlist.js';s=open(p).read();o='    if (fired) glow(rec);';assert o in s;s=s.replace(o,'    if (fired) rec.glowing = true;\n    if (rec.glowing) glow(rec);');open(p,'w').write(s)" \
  ptr=glow,rmotion the-yes-tree=glow,rmotion
