#!/usr/bin/env bash
# The R3b-2 mutant round — the DEAD-MEMBER RULE: a turn releases when its holder stops getting CLOSER.
#
# ⛔ FOR EVERY MUTANT, THE TWO QUESTIONS (V4's Part 5, kept):
#   1. CAN IT MOVE ITS ROW'S OWN REFERENCE? Every leg in `loader/cycle.test.mjs` judges the rule against the STUB's
#      own facts — the `state.can` flags and the `state.base` / `state.req` series the test itself drives, and the
#      act counts the stub records — never against `cycleState()` alone, which is a readout of the thing under test.
#      Where a leg does read `cycleState().skip` it ALSO asserts an act count, so a build that reported a release it
#      did not make still reds.
#   2. DOES A SECOND GUARD MAKE IT REDUNDANT? Named beside the ones where it does.
#
# ⛔ ONE MUTANT THAT IS DELIBERATELY NOT WRITTEN, AND WHY — the §34.5 discipline (a mutant that cannot fail is
# documented, not shipped green). `m-r3b2-static-reads-requires`: make `turnDistance` compare a STATIC layer's
# `baseAmount` against `requires` instead of `nextAt` (V1 §16.3 item 8's trap). NO LEG THIS SLICE HAS CAN SEE IT.
# At B = 0 the rule reads only whether the fraction ROSE, and both readings are monotone in `baseAmount`; the two
# bars differ only once the layer has reset (a static layer's `nextAt` climbs, its `requires` does not), and PTR's
# only static row-3 member is `ss`, which never resets at this frontier. What WOULD reach it is a stub leg with a
# `static` layer whose `nextAt` rises while its `requires` stands still, and that layer does not exist in
# `cycle.test.mjs`'s fixture yet. Recorded here so the next slice inherits the gap rather than the illusion.
#
# ⛔ RESTORED FROM A COPY, NEVER FROM GIT — a harness that restores with `git checkout` restores over uncommitted
# work. The script refuses to start on a dirty tree.
#
# ⛔ DO NOT EDIT THIS FILE WHILE IT IS RUNNING. Bash reads a script incrementally, by byte offset.
#
#   bash tools/harness/mutants-r3b2.sh <out-dir> [name-filter]
set -uo pipefail
cd "$(dirname "$0")/../.."
OUT="${1:?usage: mutants-r3b2.sh <out-dir> [name-filter]}"
ONLY="${2:-}"
mkdir -p "$OUT"
if [ -n "$(git status --porcelain)" ]; then echo "REFUSING: the tree is dirty. Commit first — a mutant round restores over whatever is here."; exit 1; fi
AUTO=loader/tmt-auto.js
cp "$AUTO" "$OUT/tmt-auto.js.orig"
restore() { cp "$OUT/tmt-auto.js.orig" "$AUTO"; }
trap restore EXIT

mutant() {
  local name="$1" mut="$2"; shift 2
  if [ -n "$ONLY" ] && [[ "$name" != *"$ONLY"* ]]; then return 0; fi
  restore
  python3 -c "$mut" || { echo "$name: THE MUTATION DID NOT APPLY"; return 1; }
  echo "=== $name ==="
  git --no-pager diff --stat -- "$AUTO"
  "$@" > "$OUT/$name.log" 2>&1
  echo "$name: exit $? — $(grep -acE '^(RED|not ok)' "$OUT/$name.log") RED row(s), $(grep -acE '^(GREEN|ok )' "$OUT/$name.log") green"
  grep -aE '^(RED|not ok)' "$OUT/$name.log" | cut -c1-260
  restore
  git --no-pager diff --stat -- "$AUTO" | grep . && echo "!! NOT RESTORED" || echo "restored: diff is empty"
}

UNIT="node --test loader/cycle.test.mjs"
# The REAL-ENGINE half. `--part 1` on the L21 fixture is where the freeze itself lives, and it is short enough
# (4,000 ticks) to drive a mutant with. ONE run per cell: a mutant round asks whether a row REDDENS.
FREEZE="node tools/harness/gates-r3b2.mjs --part 1 --no-summary --no-write --repeat21 1 --pool 2 --ticks 1"

# ---- the rule fires at all -------------------------------------------------------------------------------------
# ⛔ THE DEFECT THIS SLICE EXISTS FOR, AS A MUTATION: the plateau branch removed, so a holder the engine refuses
# keeps the turn for ever. This is the state BEFORE the slice, and it is the freeze measured in §39.
# It must redden the stub's plateau leg AND the real-engine freeze row — two references, one defect.
mutant m-r3b2-a-refused-holder-is-never-released \
  "p='$AUTO';s=open(p).read();o='          if (hold > 0 && (now - C.closer) >= hold) endTurn(C, C.holder, \'released\');';assert o in s, 'anchor';s=s.replace(o,'          if (false) endTurn(C, C.holder, \'released\');');open(p,'w').write(s)" \
  $UNIT

# ⛔ AND THE OPPOSITE FAILURE, WHICH IS THE EXPENSIVE ONE: a holder that IS closing distance is released anyway —
# `h` starved, the state §32.1 item 2 measured at Hindrance Spirit ONE. The re-anchor never fires, so every refused
# holder loses its turn one window after it is granted.
# ⚠ THE REFERENCE IS THE CONSTRUCTED CLIMB, NOT THE MUTANT'S OWN HISTORY — the stub leg drives `state.base` itself.
mutant m-r3b2-a-climbing-holder-is-released \
  "p='$AUTO';s=open(p).read();o='    if (p - best > need || p < best) { C.best[f.id] = p; C.closer = now; }';assert o in s, 'anchor';s=s.replace(o,'    if (false) { C.best[f.id] = p; C.closer = now; }');open(p,'w').write(s)" \
  $UNIT

# ---- the anchor ---------------------------------------------------------------------------------------------------
# ⛔ A SIBLING'S WIPE COUNTED AS "NOT GETTING CLOSER". The brief asks this question out loud and the answer is NO:
# PTR's `h` loses base MID-TURN to row-2 spending it does not control (3.23e20 → 2.03e19 between two samples 25
# game-seconds apart, measured while `h` held the turn), and against a high-water that only ever rises those losses
# accumulate until the re-climb cannot beat it inside H.
mutant m-r3b2-wipe-costs-the-turn \
  "p='$AUTO';s=open(p).read();o='    if (p - best > need || p < best) { C.best[f.id] = p; C.closer = now; }';assert o in s, 'anchor';s=s.replace(o,'    if (p - best > need) { C.best[f.id] = p; C.closer = now; }');open(p,'w').write(s)" \
  $UNIT

# ⛔ THE ANCHOR RESET WITH EVERY TURN, i.e. "did it climb since this turn began" rather than "is it better than it
# has ever been". That is TRUE OF THE DEAD MEMBERS — `o` climbs 0 → 5 of 14 on every turn it is given, because
# holding the turn is what stops a sibling wiping the row below — so the rule stops discriminating and the row
# spends a full climb on each dead member every rotation.
mutant m-r3b2-best-forgotten-each-turn \
  "p='$AUTO';s=open(p).read();o='    C.closer = C.since;';assert o in s, 'anchor';s=s.replace(o,'    C.closer = C.since; if (C.best) delete C.best[f.id];');open(p,'w').write(s)" \
  $FREEZE

# ---- which refusal the rule is about --------------------------------------------------------------------------
# ⛔ THE RULE LOOKING WHILE THE ENGINE WOULD ALLOW. §34.2 item 1: "my rule says not yet" is productive waiting and
# the weight exists to protect it — a member on `gain>=2` whose gain is momentarily 1 would lose its turn every
# window, which is the defect that made weight 5 and weight 20 the same run.
mutant m-r3b2-rule-ignores-the-engine \
  "p='$AUTO';s=open(p).read();o='        if (!engineAllows(h)) {';assert o in s, 'anchor';s=s.replace(o,'        if (true) {');open(p,'w').write(s)" \
  $UNIT

# ⛔ AND THE THRESHOLD READ OFF THE WRONG SIDE: `nextAt` for a NORMAL layer. `canReset` compares a normal layer's
# base against `requires`, and on PTR's `q` the two are different numbers — so the fraction would be measured
# against a bar the engine does not use, and a member could read "arrived" while the engine still refused it.
mutant m-r3b2-normal-reads-nextat \
  "p='$AUTO';s=open(p).read();o=\"    var goal = t.type === 'static' ? t.nextAt : t.type === 'normal' ? t.requires : null;\";assert o in s, 'anchor';s=s.replace(o,\"    var goal = t.nextAt;\");open(p,'w').write(s)" \
  $FREEZE
