#!/usr/bin/env bash
# The V5 mutant round — the Advanced tab's WRAP, its no-JUMP floors, the RETRY conditions, and R3b-1's owed m17 cell.
#
# ⛔ FOR EVERY MUTANT, THE TWO QUESTIONS (V4's Part 5, kept):
#   1. CAN IT MOVE ITS ROW'S OWN REFERENCE? Part 1 judges against the VIEWPORT and the engine's own PANE (neither is
#      drawn by the loader) and against tap-target sizes declared from a pre-V5 measurement; part 2 judges one render
#      against the previous render of the SAME page, and its CONTROL rows switch the floors off in a second page —
#      a mutant that broke the switch would red the control instead of passing it; the retry rows judge against the
#      stub's own `canReset` flags and act counts, which the loader cannot touch.
#   2. DOES A SECOND GUARD MAKE IT REDUNDANT? Named beside the ones where it does.
#
# ⛔ RESTORED FROM A COPY, NEVER FROM GIT — a harness that restores with `git checkout` restores over uncommitted
# work. The script refuses to start on a dirty tree. ⛔ DO NOT EDIT THIS FILE WHILE IT IS RUNNING (bash reads it by
# byte offset).
#
#   bash tools/harness/mutants-v5.sh <out-dir> [name-filter]
set -uo pipefail
cd "$(dirname "$0")/../.."
OUT="${1:?usage: mutants-v5.sh <out-dir> [name-filter]}"
ONLY="${2:-}"
mkdir -p "$OUT"
if [ -n "$(git status --porcelain)" ]; then echo "REFUSING: the tree is dirty. Commit first — a mutant round restores over whatever is here."; exit 1; fi
AUTO=loader/tmt-auto.js
cp "$AUTO" "$OUT/tmt-auto.js.orig"
restore() { cp "$OUT/tmt-auto.js.orig" "$AUTO"; }
trap restore EXIT

mutant() {
  local name="$1" mut="$2"; shift 2
  if [ -n "$ONLY" ] && [[ "$name" != *"$ONLY"* ]]; then return 0; fi
  restore
  python3 -c "$mut" || { echo "$name: THE MUTATION DID NOT APPLY"; return 1; }
  echo "=== $name ==="
  git --no-pager diff --stat -- "$AUTO"
  "$@" > "$OUT/$name.log" 2>&1
  echo "$name: exit $? — $(grep -cE '^(RED|not ok)' "$OUT/$name.log") RED row(s), $(grep -cE '^(GREEN|ok )' "$OUT/$name.log") green"
  grep -E '^(RED|not ok)' "$OUT/$name.log" | cut -c1-240
  restore
  git --no-pager diff --stat -- "$AUTO" | grep . && echo "!! NOT RESTORED" || echo "restored: diff is empty"
}

WRAP="node tools/harness/gates-v5.mjs --part 1 --no-summary --no-write"
JUMP="node tools/harness/gates-v5.mjs --part 2 --no-summary --no-write --playTicks 20"
UNIT="node --test loader/retry.test.mjs loader/challenges.test.mjs"
RATIO="node tools/harness/gates-r3b.mjs --part 7 --no-summary --no-write --repeat7 1 --pool 3"

# ---- Part 1: the WRAP ------------------------------------------------------------------------------------------------
# ⛔ THE BRIEF'S OWN MUTANT: one label is `white-space: nowrap` again. It must red the PHONE rows (390, with and without
# `?mobile=1`, both games) and NOT the desktop rows — a leg that reds everywhere would be asserting something that is
# always true of a long label, not something about the phone.
mutant m1-a-label-is-nowrap-again \
  "p='$AUTO';s=open(p).read();o='<span class=\"tmtl-label\" style=\"opacity:.75;font-size:.85em;min-width:0;';assert o in s;s=s.replace(o,'<span class=\"tmtl-label\" style=\"white-space:nowrap;opacity:.75;font-size:.85em;min-width:0;');open(p,'w').write(s)" \
  $WRAP

# the ROOT sizes its own column again (the pre-V5 root) — desktop and 390-plain must red, `?mobile=1` alone is spared
# by mobile.css's `.upgCol` clamp (a SECOND guard, on that one view only)
mutant m2-the-root-takes-its-max-content-width \
  "p='$AUTO';s=open(p).read();o=\";display:table;table-layout:fixed;width:100%;box-sizing:border-box';\";assert o in s;s=s.replace(o,\"';\");open(p,'w').write(s)" \
  $WRAP

# ⛔ THE VACUOUS GREEN: `contain:inline-size` instead of the table. Nothing is past the edge because the column is
# 0 px wide — the "root is its pane's width" check is the ONLY thing that can see it.
mutant m3-contain-inline-size-collapses-the-column \
  "p='$AUTO';s=open(p).read();o=\";display:table;table-layout:fixed;width:100%;box-sizing:border-box';\";assert o in s;s=s.replace(o,\";contain:inline-size;width:100%;box-sizing:border-box';\");open(p,'w').write(s)" \
  $WRAP

# ---- Part 2: NO JUMP -------------------------------------------------------------------------------------------------
# ⛔ THE BRIEF'S OWN MUTANT: the floor is written into the HTML string — a fresh floor every render, so it remembers
# nothing across a redraw. It must red the floors-ON rows (shrink, swap, vanish) and leave the CONTROL rows green.
mutant m4-the-floor-lives-in-the-html-string \
  "p='$AUTO';s=open(p).read();o='    var F = fl || null;\n    return (collapsed';assert o in s;s=s.replace(o,'    var F = fl ? T.newFloors() : null;\n    return (collapsed');open(p,'w').write(s)" \
  $JUMP

# the LINE slots gone, the number boxes kept — sentence and line rows must red, the number rows must not
mutant m5-no-line-slots \
  "p='$AUTO';s=open(p).read();o='    if (!F || !FLOORS_ON) return html || \'\';\n    var g = F.g[key];';assert o in s;s=s.replace(o,'    return html || \'\';\n    var g = F.g[key];');open(p,'w').write(s)" \
  $JUMP

# a number floor that does not GROW-ONLY (the width of the string now) — the shrink row must red
mutant m6-the-number-floor-follows-the-string \
  "p='$AUTO';s=open(p).read();o='if (F && FLOORS_ON) { mw = F.w[key] || 0; if (t.length > mw) F.w[key] = mw = t.length; }';assert o in s;s=s.replace(o,'if (F && FLOORS_ON) { mw = t.length; }');open(p,'w').write(s)" \
  $JUMP

# ---- Part 3: the RETRY conditions ------------------------------------------------------------------------------------
# the count starts from the WHOLE counter, not from the give-up — resets made during the failed attempt count
mutant m7-count-from-the-total \
  "p='$AUTO';s=open(p).read();o='    for (var i = 0; i < watch.length; i++) seen[watch[i]] = actionsOf(watch[i]);';assert o in s;s=s.replace(o,'    for (var i = 0; i < watch.length; i++) seen[watch[i]] = 0;');open(p,'w').write(s)" \
  $UNIT

# every reset feature counts, whatever its row
mutant m8-count-every-reset-feature \
  "p='$AUTO';s=open(p).read();o='      if (n > was && inRow[fid]) r.done += n - was;';assert o in s;s=s.replace(o,'      if (n > was) r.done += n - was;');open(p,'w').write(s)" \
  $UNIT

# nothing frozen — the frozen reading re-reads the row every time, as `-now` does
mutant m9-nothing-frozen \
  "p='$AUTO';s=open(p).read();o='    if (live) { var H = highestResetRow();';assert o in s;s=s.replace(o,'    if (true) { var H = highestResetRow();');open(p,'w').write(s)" \
  $UNIT

# a counter that went BACKWARDS (a resume that lost it) is subtracted rather than re-read
mutant m10-a-backwards-counter-is-subtracted \
  "p='$AUTO';s=open(p).read();o='      if (n > was && inRow[fid]) r.done += n - was;';assert o in s;s=s.replace(o,'      if (inRow[fid]) r.done += n - was;');open(p,'w').write(s)" \
  $UNIT

# R3a's row writes an OBJECT like the others — its record (and every committed snapshot's) would change shape
mutant m11-every-condition-writes-an-object \
  "p='$AUTO';s=open(p).read();o='      seed: function (f, P, now, startHeld) { return startHeld; },';assert o in s;s=s.replace(o,'      seed: function (f, P, now, startHeld) { return { held: startHeld }; },');open(p,'w').write(s)" \
  $UNIT

# the predicate is ignored — `when` retries at once whatever it says
mutant m12-the-retry-predicate-is-ignored \
  "p='$AUTO';s=open(p).read();o='        return v.value ? null : { code: \'waiting:retry-when\'';assert o in s;s=s.replace(o,'        return true ? null : { code: \'waiting:retry-when\'');open(p,'w').write(s)" \
  $UNIT

# a retry predicate that THROWS reads as false — V4's trap, in the new place
mutant m13-a-throwing-retry-predicate-reads-as-false \
  "p='$AUTO';s=open(p).read();o='        if (v.error) return { code: \'blocked:retry-when\'';assert o in s;s=s.replace(o,'        if (false) return { code: \'blocked:retry-when\'');open(p,'w').write(s)" \
  $UNIT

# ---- R3b-1's owed cell: m17, at last with a row that can see it -------------------------------------------------------
# ⛔ The guard clock from the TURN'S START rather than the holder's LAST ACT. At K = 30 a twenty-reset turn never
# reaches the bound (R3b-1 measured it GREEN against part 7); the `turn@60` cell V5 added outlasts it. Only the W=60
# row should red — the two guard-off cells (K = 100000) cannot consult a clock at all.
mutant m17-guard-clock-from-the-turn-start \
  "p='$AUTO';s=open(p).read();o='        var sinceAct = C.acted === null || C.acted === undefined ? C.since : C.acted;';assert o in s;s=s.replace(o,'        var sinceAct = C.since;');open(p,'w').write(s)" \
  $RATIO

echo
echo "⛔ READ EVERY LINE ABOVE. A mutant that comes back GREEN is a gate that cannot see the defect it was written"
echo "   for, and the answer is a NEW ROW — not a note."
