#!/usr/bin/env bash
# The R3b-1 mutant round — the ROW CYCLE: turn-taking between same-row resets, its guard, and its demand link.
#
# ⛔ FOR EVERY MUTANT, THE TWO QUESTIONS (V4's Part 5, kept):
#   1. CAN IT MOVE ITS ROW'S OWN REFERENCE? Every row in `loader/cycle.test.mjs` is judged against something the
#      LOADER cannot touch — the stub's own `canReset` flags, the act counts the stub records, the `player` the
#      stub owns — or against a CONTROL built in the same test (the demand row measures two builds against each
#      other, and the weights build is the reference). The cycle's own `cycleState()` is a readout of the thing
#      under test, so no row rests on it alone: every one of them also asserts an ACT COUNT or an ENGINE fact.
#   2. DOES A SECOND GUARD MAKE IT REDUNDANT? Named beside the ones where it does. A mutant that only changes a
#      LABEL is excluded on purpose: `waiting:turn` is asserted in the vocabulary table AND as a value on a real
#      decision, so dropping it reddens two rows and proves nothing about the mechanism.
#
# ⛔ RESTORED FROM A COPY, NEVER FROM GIT — a harness that restores with `git checkout` restores over uncommitted
# work. The script refuses to start on a dirty tree, because a dirty tree is the case where the copy is the only
# thing between the mutation and the work.
#
# ⛔ DO NOT EDIT THIS FILE WHILE IT IS RUNNING. Bash reads a script incrementally, by byte offset.
#
#   bash tools/harness/mutants-r3b.sh <out-dir> [name-filter]
set -uo pipefail
cd "$(dirname "$0")/../.."
OUT="${1:?usage: mutants-r3b.sh <out-dir> [name-filter]}"
ONLY="${2:-}"
mkdir -p "$OUT"
if [ -n "$(git status --porcelain)" ]; then echo "REFUSING: the tree is dirty. Commit first — a mutant round restores over whatever is here."; exit 1; fi
AUTO=loader/tmt-auto.js
cp "$AUTO" "$OUT/tmt-auto.js.orig"
restore() { cp "$OUT/tmt-auto.js.orig" "$AUTO"; }
trap restore EXIT

mutant() {
  local name="$1" mut="$2"; shift 2
  if [ -n "$ONLY" ] && [[ "$name" != *"$ONLY"* ]]; then return 0; fi
  restore
  python3 -c "$mut" || { echo "$name: THE MUTATION DID NOT APPLY"; return 1; }
  echo "=== $name ==="
  git --no-pager diff --stat -- "$AUTO"
  "$@" > "$OUT/$name.log" 2>&1
  echo "$name: exit $? — $(grep -cE '^(RED|not ok)' "$OUT/$name.log") RED row(s), $(grep -cE '^(GREEN|ok )' "$OUT/$name.log") green"
  grep -E '^(RED|not ok)' "$OUT/$name.log" | cut -c1-260
  restore
  git --no-pager diff --stat -- "$AUTO" | grep . && echo "!! NOT RESTORED" || echo "restored: diff is empty"
}

UNIT="node --test loader/cycle.test.mjs"

# ---- R1: the cycle binds EVERY member --------------------------------------------------------------------------
# ⛔ THE PLANNER'S OWN VOID CELL, AS A MUTATION. Three of its nine cells gated only `q`; the eager `reset:h` that was
# left out fired 44 times and wiped row 2 before `q`'s turn could be used. "Members are the carriers" is exactly
# that build.
mutant m1-members-are-carriers-only \
  "p='$AUTO';s=open(p).read();o='      by[key].members.push(g);\n      var m = turnMod(g);';assert o in s;s=s.replace(o,'      var m = turnMod(g);\n      if (m) by[key].members.push(g);');open(p,'w').write(s)" \
  $UNIT

# ⛔ AND THE OTHER HALF OF R1: a cycle keyed by the LAYER rather than by the ROW. Every member gets its own cycle,
# every member always holds its own turn, and nobody ever waits — a scheduler that schedules nothing, green in every
# hash and in every mark. No second guard sees it: the act counts are unchanged from the no-cycle control.
mutant m2-cycle-keyed-by-layer \
  "p='$AUTO';s=open(p).read();o='      var key = String(r);';assert o in s;s=s.replace(o,'      var key = String(g.layer);');open(p,'w').write(s)" \
  $UNIT

# ---- R2: a member is EAGER inside its turn ---------------------------------------------------------------------
# ⛔ THE REQUIREMENT'S OWN NEGATION, and the deadlock the planner measured: a patient rule inside a turn never fires
# (`gain>=2x` on a layer whose gain is small against what it holds), so the turn is never spent and the cycle stops.
mutant m3-patient-inside-the-turn \
  "p='$AUTO';s=open(p).read();o='    if (turn) return turn.act ? { act: true, rule: %sin-turn%s } : turn;'.replace('%s',chr(39));assert o in s;s=s.replace(o,'    if (turn && !turn.act) return turn;');open(p,'w').write(s)" \
  $UNIT

# ⚠ THE SUBTLER HALF: the cycle is checked BEFORE the engine. `waiting:turn` then hides the fact that the game
# itself is refusing, and a member that could never reset looks like one that is merely waiting its turn. It moves
# no act count at all — the only thing that sees it is the code on the refusal.
mutant m4-cycle-above-the-engine \
  "p='$AUTO';s=open(p).read();o='    if (!tmp[l] || tmp[l].canReset !== true) {';assert o in s;i=s.index(o);j=s.index('    var turn = turnStep(f);',i);k=s.index('\n',s.index('if (turn) return turn.act',j));blk=s[j:k+1];s=s[:j]+s[k+1:];s=s[:i]+blk+s[i:];open(p,'w').write(s)" \
  $UNIT

# ---- R3: the guard ---------------------------------------------------------------------------------------------
# ⛔ A RELEASED TURN FEEDS THE TYPICAL — `stall>=Kx/N`'s own defect one level up: the bound grows with every timeout
# and the guard stops guarding. ⚠ It is invisible on a SHORT leg (the first release is still released on time), which
# is why the row that sees it runs long enough for the median to move.
mutant m5-released-turn-feeds-the-typical \
  "p='$AUTO';s=open(p).read();o=\"    if (how === 'complete' && C.since !== null) {\";assert o in s;s=s.replace(o,\"    if (how !== 'ineligible' && C.since !== null) {\");open(p,'w').write(s)" \
  $UNIT

# ⛔ THE GUARD IS SILENT WITHOUT A TYPICAL — first-cycle blindness, which R2 §24.11 item 4 named and which this
# slice was told not to repeat silently. The first turn is then unbounded and a holder that can never act holds for
# ever. No second guard sees it: once one turn HAS completed the median rule takes over and every other row is green.
mutant m6-no-first-cycle-rule \
  "p='$AUTO';s=open(p).read();o='        else if (typ === null && !engineAllows(h)) {';assert o in s;s=s.replace(o,'        else if (false) {');open(p,'w').write(s)" \
  $UNIT

# ⚠ A TYPICAL OF ZERO IS A BOUND. This is the defect the stub found while the slice was being built: a one-reset
# turn granted and spent inside the same tick is zero game-seconds long, so `K × 0 = 0` releases every turn on the
# tick it was granted — before its holder's layer has run.
mutant m7-zero-is-a-bound \
  "p='$AUTO';s=open(p).read();o='  function medianPos(xs) { if (!xs || !xs.length) return null; var m = median(xs); return m > 0 ? m : null; }';assert o in s;s=s.replace(o,'  function medianPos(xs) { if (!xs || !xs.length) return null; return median(xs); }');open(p,'w').write(s)" \
  $UNIT

# ⛔ A RELEASED MEMBER IS NOT SKIPPED. A demand that can never be met then hands the turn straight back on the very
# next tick, for ever, and no other member is reached again.
mutant m8-no-skip-after-a-release \
  "p='$AUTO';s=open(p).read();o=\"    if (how === 'released') C.skip[id] = C.round + Math.max(1, C.ids.length);\";assert o in s;s=s.replace(o,'');open(p,'w').write(s)" \
  $UNIT

# ⛔ AND ITS MIRROR, WHICH IS THE ONE THAT ACTUALLY SHIPPED FOR AN HOUR: a DEMAND preemption skips the member it
# interrupted. Every member ends up skipped, the one holder that cannot act has nobody eligible to release the turn
# to, and the cycle deadlocks — green in every hash, and the reason the four turn-endings exist.
mutant m9-preemption-skips-the-preempted \
  "p='$AUTO';s=open(p).read();o=\"if (C.holder) endTurn(C, C.holder, 'preempted');\";assert o in s;s=s.replace(o,\"if (C.holder) endTurn(C, C.holder, 'released');\");open(p,'w').write(s)" \
  $UNIT

# ---- R4: the memory is the LOADER's own -------------------------------------------------------------------------
# ⛔ THE TRAP THE PLANNER'S SIX VOID CELLS FELL INTO, AS A MUTATION. `player[l].resetTime` exists ONLY on the
# 2.7-style engine; on the stub and on ptr it is `undefined`, so the typical is never a number and the guard never
# fires. ⚠ A build with this defect would be GREEN on `something` — which is why `gates-r3b --part 2` runs the same
# four legs on BOTH engine families and why that is R4 rather than a note.
mutant m10-typical-from-an-engine-field \
  "p='$AUTO';s=open(p).read();o='  function ownTypical(C, f) { return medianPos(C.mem[f.id]); }';assert o in s;s=s.replace(o,'  function ownTypical(C, f) { var t = player[f.layer] && player[f.layer].resetTime; return t === undefined ? null : Number(t); }\n  function unusedOwnTypical(C, f) { return medianPos(C.mem[f.id]); }');s=s.replace('  function typicalTurn(C, f) {\n    var own = medianPos(C.mem[f.id]);','  function typicalTurn(C, f) {\n    var own = ownTypical(C, f);');open(p,'w').write(s)" \
  $UNIT

# ⛔ THE MEMORY IS NOT IN `runtimeState()`. A resumed run then takes a different path from an uninterrupted one, and
# every committed snapshot that carries a cycle is silently wrong. Nothing in a single-process leg can see it, which
# is why the row asserts the KEY SET and the round trip rather than "something round-trips".
mutant m11-no-runtime-memory \
  "p='$AUTO';s=open(p).read();o='    if (ncy) o.cycle = cy;';assert o in s;s=s.replace(o,'');open(p,'w').write(s)" \
  $UNIT

# ---- DORMANCY and INERTNESS ---------------------------------------------------------------------------------------
# ⛔ A CYCLE OF ONE IS A CYCLE. Since a member is eager inside its turn, a lone member's policy silently becomes
# `always` — and on PTR that is `reset:q`'s measured `gain>=2` replaced by the rule R2 measured reaching M16 NEVER,
# for the whole M15 → M21 stretch, with `reset:h` still locked.
mutant m12-a-cycle-of-one \
  "p='$AUTO';s=open(p).read();o='      var active2 = R.members.length >= 2;';assert o in s;s=s.replace(o,'      var active2 = R.members.length >= 1;');open(p,'w').write(s)" \
  $UNIT

# ⛔ INERTNESS: a cycle is derived for every row whether anything asked for it or not. Every reset in the game is
# suddenly scheduled, and the claim "everything new is OFF until a table or a player turns it on" is false.
mutant m13-a-cycle-on-every-row \
  "p='$AUTO';s=open(p).read();o='    for (var j = 0; j < order.length; j++) if (rows_on(by, order[j])) out.push(by[order[j]]);';s2='    for (var j = 0; j < order.length; j++) if (by[order[j]].on) out.push(by[order[j]]);';assert s2 in s;s=s.replace(s2,'    for (var j = 0; j < order.length; j++) out.push(by[order[j]]);');open(p,'w').write(s)" \
  $UNIT

# ---- DEMAND --------------------------------------------------------------------------------------------------------
# ⛔ DEMAND ONLY SPEAKS WHEN NOBODY HOLDS THE TURN. It then never moves anything — a member with a heavy weight holds
# the turn from the first tick and the layer something is waiting on never gets one. The two variants stop being
# distinguishable, which is the whole of Part 2.
mutant m14-demand-only-when-idle \
  "p='$AUTO';s=open(p).read();o='      if (C.demand) { var d = demandedMember(C, R); if (d && d.id !== C.holder)';assert o in s;s=s.replace(o,'      if (C.demand && !C.holder) { var d = demandedMember(C, R); if (d && d.id !== C.holder)');open(p,'w').write(s)" \
  $UNIT

# ⛔ A DEMAND SIGNAL IS "ANY VALUE THAT LOOKS LIKE A LAYER" rather than the one the CODE declares. The cycle then
# reads `yielding:native`'s layer, `waiting:stall-yield`'s layer and its OWN `waiting:turn` as demands — and the
# last of those feeds itself, so the holder demands its own turn for ever.
mutant m15-demand-is-any-layer-shaped-value \
  "p='$AUTO';s=open(p).read();o='      if (!last || !CODES[last.code] || !CODES[last.code].demand) continue;\n      var v = last.values && last.values[CODES[last.code].demand];\n      if (typeof v === %ss%s && v) want[v] = true;'.replace('%ss%s',chr(39)+'string'+chr(39));assert o in s;s=s.replace(o,'      if (!last || !last.values) continue;\n      for (var vk in last.values) { var v = last.values[vk]; if (typeof v === '+chr(39)+'string'+chr(39)+' && v && layers[v]) want[v] = true; }');open(p,'w').write(s)" \
  $UNIT

echo
echo "⛔ READ EVERY LINE ABOVE. A mutant that comes back GREEN is a gate that cannot see the defect it was written"
echo "   for, and the answer is a NEW ROW — not a note. R3a's round had two survivors on its first pass."
