#!/usr/bin/env bash
# The R3b-1 mutant round — the ROW CYCLE: turn-taking between same-row resets, its guard, and its demand link.
#
# ⛔ FOR EVERY MUTANT, THE TWO QUESTIONS (V4's Part 5, kept):
#   1. CAN IT MOVE ITS ROW'S OWN REFERENCE? Every row in `loader/cycle.test.mjs` is judged against something the
#      LOADER cannot touch — the stub's own `canReset` flags, the act counts the stub records, the `player` the
#      stub owns — or against a CONTROL built in the same test (the demand row measures two builds against each
#      other, and the weights build is the reference). The cycle's own `cycleState()` is a readout of the thing
#      under test, so no row rests on it alone: every one of them also asserts an ACT COUNT or an ENGINE fact.
#   2. DOES A SECOND GUARD MAKE IT REDUNDANT? Named beside the ones where it does. A mutant that only changes a
#      LABEL is excluded on purpose: `waiting:turn` is asserted in the vocabulary table AND as a value on a real
#      decision, so dropping it reddens two rows and proves nothing about the mechanism.
#
# ⛔ RESTORED FROM A COPY, NEVER FROM GIT — a harness that restores with `git checkout` restores over uncommitted
# work. The script refuses to start on a dirty tree, because a dirty tree is the case where the copy is the only
# thing between the mutation and the work.
#
# ⛔ DO NOT EDIT THIS FILE WHILE IT IS RUNNING. Bash reads a script incrementally, by byte offset.
#
#   bash tools/harness/mutants-r3b.sh <out-dir> [name-filter]
set -uo pipefail
cd "$(dirname "$0")/../.."
OUT="${1:?usage: mutants-r3b.sh <out-dir> [name-filter]}"
ONLY="${2:-}"
mkdir -p "$OUT"
if [ -n "$(git status --porcelain)" ]; then echo "REFUSING: the tree is dirty. Commit first — a mutant round restores over whatever is here."; exit 1; fi
AUTO=loader/tmt-auto.js
cp "$AUTO" "$OUT/tmt-auto.js.orig"
restore() { cp "$OUT/tmt-auto.js.orig" "$AUTO"; }
trap restore EXIT

mutant() {
  local name="$1" mut="$2"; shift 2
  if [ -n "$ONLY" ] && [[ "$name" != *"$ONLY"* ]]; then return 0; fi
  restore
  python3 -c "$mut" || { echo "$name: THE MUTATION DID NOT APPLY"; return 1; }
  echo "=== $name ==="
  git --no-pager diff --stat -- "$AUTO"
  "$@" > "$OUT/$name.log" 2>&1
  echo "$name: exit $? — $(grep -cE '^(RED|not ok)' "$OUT/$name.log") RED row(s), $(grep -cE '^(GREEN|ok )' "$OUT/$name.log") green"
  grep -E '^(RED|not ok)' "$OUT/$name.log" | cut -c1-260
  restore
  git --no-pager diff --stat -- "$AUTO" | grep . && echo "!! NOT RESTORED" || echo "restored: diff is empty"
}

UNIT="node --test loader/cycle.test.mjs"
# ⛔ THE WHOLE-STRETCH RATIO ROW. Two defects of this slice are invisible to every stub leg (§34), so their mutants
# are driven by the gate that can see them. ONE run per cell: a mutant round asks whether a row RED-dens, and a
# twice-equal check is the row's own business when it runs for real.
RATIO="node tools/harness/gates-r3b.mjs --part 7 --no-summary --no-write --repeat7 1 --pool 2"

# ---- R1: the cycle binds EVERY member --------------------------------------------------------------------------
# ⛔ THE PLANNER'S OWN VOID CELL, AS A MUTATION. Three of its nine cells gated only `q`; the eager `reset:h` that was
# left out fired 44 times and wiped row 2 before `q`'s turn could be used. "Members are the carriers" is exactly
# that build.
mutant m1-members-are-carriers-only \
  "p='$AUTO';s=open(p).read();o='      by[key].members.push(g);\n      var m = turnMod(g);';assert o in s;s=s.replace(o,'      var m = turnMod(g);\n      if (m) by[key].members.push(g);');open(p,'w').write(s)" \
  $UNIT

# ⛔ AND THE OTHER HALF OF R1: a cycle keyed by the LAYER rather than by the ROW. Every member gets its own cycle,
# every member always holds its own turn, and nobody ever waits — a scheduler that schedules nothing, green in every
# hash and in every mark. No second guard sees it: the act counts are unchanged from the no-cycle control.
mutant m2-cycle-keyed-by-layer \
  "p='$AUTO';s=open(p).read();o='      var key = String(r);';assert o in s;s=s.replace(o,'      var key = String(g.layer);');open(p,'w').write(s)" \
  $UNIT

# ---- R2: a member decides by its OWN policy inside its turn -----------------------------------------------------
# ⛔ THE BRIEF'S OWN REQUIREMENT, AS A MUTATION, because the whole-stretch sweep overturned it: eager-in-turn
# silently replaces PTR's measured `reset:q` policy `gain>=2` with `always` and `q` resets for ONE quirk instead of
# two (249 quirks from 244 resets against the control's 559 from 279).
mutant m3-eager-inside-the-turn \
  "p='$AUTO';s=open(p).read();o='    if (turn && !turn.act) return turn;';assert o in s;s=s.replace(o,'    if (turn) return turn.act ? { act: true, rule: '+chr(39)+'always'+chr(39)+' } : turn;');open(p,'w').write(s)" \
  $UNIT

# ⚠ … AND ITS MIRROR: the holder yields whenever it cannot act, ENGINE refusal included. That is the rule the
# whole-stretch sweep measured as starvation — PTR's `h` is released before Time Energy can ever reach 1e30, and
# Hindrance Spirit ends at ONE, which is the state before this slice.
mutant m3c-yield-on-an-engine-refusal-too \
  "p='$AUTO';s=open(p).read();o='    if (!tmp[l] || tmp[l].canReset !== true) {';assert o in s;s=s.replace(o,'    if (!tmp[l] || tmp[l].canReset !== true) { turnYield(f);');open(p,'w').write(s)" \
  $UNIT

# ⚠ THE SUBTLER HALF: the cycle is checked BEFORE the engine. `waiting:turn` then hides the fact that the game
# itself is refusing, and a member that could never reset looks like one that is merely waiting its turn. It moves
# no act count at all — the only thing that sees it is the code on the refusal.
mutant m4-cycle-above-the-engine \
  "p='$AUTO';s=open(p).read();o='    if (!tmp[l] || tmp[l].canReset !== true) {';assert o in s;i=s.index(o);j=s.index('    var turn = turnStep(f);',i);k=s.index('\n',s.index('if (turn) return turn.act',j));blk=s[j:k+1];s=s[:j]+s[k+1:];s=s[:i]+blk+s[i:];open(p,'w').write(s)" \
  $UNIT

# ---- R3: the guard ---------------------------------------------------------------------------------------------
# ⛔ THE TYPICAL IS THE TURN'S LENGTH RATHER THAN THE WAIT BETWEEN THE MEMBER'S OWN RESETS. A turn of weight W
# spans W resets, so the bound comes out W times too large and the guard stops guarding at exactly the weight a
# table is most likely to choose. ⚠ Only a leg with W > 1 can see it.
mutant m5-the-typical-is-the-TURN-length-not-the-reset-interval \
  "p='$AUTO';s=open(p).read();o='    var dt = (Number(player.timePlayed) || 0) - prev;';assert o in s;s=s.replace(o,'    var dt = (Number(player.timePlayed) || 0) - (C.since === null ? prev : C.since);');open(p,'w').write(s)" \
  $UNIT

# ⛔ THE BOUND FALLS BACK TO THE ROW'S POOLED INTERVALS when a member has none of its own — which is the rule the
# whole-stretch sweep condemned: PTR's `h` needs ~1,450 quiet game-seconds and `q`'s resets are tens of seconds
# apart, so the pooled median is two orders of magnitude too small and `h`'s turn is released before it could
# possibly use it. Hindrance Spirit ends at ONE, the state before this slice.
mutant m6-the-bound-falls-back-to-the-ROWs-pooled-intervals \
  "p='$AUTO';s=open(p).read();o='  function typicalTurn(C, f) { return medianPos(C.mem[f.id]); }';assert o in s;s=s.replace(o,'  function typicalTurn(C, f) { var own = medianPos(C.mem[f.id]); if (own !== null) return own; var pool = []; for (var k in C.mem) pool = pool.concat(C.mem[k]); return medianPos(pool); }');open(p,'w').write(s)" \
  $UNIT

# ⚠ A ZERO INTERVAL IS REMEMBERED, so `K × 0 = 0` releases every turn on the tick it was granted — before its
# holder's layer has run. Two resets land inside one game-second whenever `diff` is 0, which is a real leg.
# ⚠ The first cut guarded this TWICE (here and on the median) and the mutant round found the second one
# redundant: a guard no leg can redden is not a guard. There is one place now.
mutant m7-a-zero-interval-is-remembered \
  "p='$AUTO';s=open(p).read();o='    if (!(dt > 0)) return;';assert o in s;s=s.replace(o,'    if (dt < 0) return;');open(p,'w').write(s)" \
  $UNIT

# ⛔ A RELEASED MEMBER IS NOT SKIPPED. A demand that can never be met then hands the turn straight back on the very
# next tick, for ever, and no other member is reached again.
mutant m8-no-skip-after-a-release \
  "p='$AUTO';s=open(p).read();o=\"    if (how === 'released') C.skip[id] = C.round + Math.max(1, C.ids.length);\";assert o in s;s=s.replace(o,'');open(p,'w').write(s)" \
  $UNIT

# ⛔ AND ITS MIRROR, WHICH IS THE ONE THAT ACTUALLY SHIPPED FOR AN HOUR: a DEMAND preemption skips the member it
# interrupted. Every member ends up skipped, the one holder that cannot act has nobody eligible to release the turn
# to, and the cycle deadlocks — green in every hash, and the reason the four turn-endings exist.
mutant m9-preemption-skips-the-preempted \
  "p='$AUTO';s=open(p).read();o=\"if (C.holder) endTurn(C, C.holder, 'preempted');\";assert o in s;s=s.replace(o,\"if (C.holder) endTurn(C, C.holder, 'released');\");open(p,'w').write(s)" \
  $UNIT

# ---- R4: the memory is the LOADER's own -------------------------------------------------------------------------
# ⛔ THE TRAP THE PLANNER'S SIX VOID CELLS FELL INTO, AS A MUTATION. `player[l].resetTime` exists ONLY on the
# 2.7-style engine; on the stub and on ptr it is `undefined`, so the typical is never a number and the guard never
# fires. ⚠ A build with this defect would be GREEN on `something` — which is why `gates-r3b --part 2` runs the same
# four legs on BOTH engine families and why that is R4 rather than a note.
mutant m10-typical-from-an-engine-field \
  "p='$AUTO';s=open(p).read();o='  function typicalTurn(C, f) { return medianPos(C.mem[f.id]); }';assert o in s;s=s.replace(o,'  function typicalTurn(C, f) { var t = player[f.layer] && player[f.layer].resetTime; return t === undefined ? null : Number(t); }');open(p,'w').write(s)" \
  $UNIT

# ⛔ THE MEMORY IS NOT IN `runtimeState()`. A resumed run then takes a different path from an uninterrupted one, and
# every committed snapshot that carries a cycle is silently wrong. Nothing in a single-process leg can see it, which
# is why the row asserts the KEY SET and the round trip rather than "something round-trips".
mutant m11-no-runtime-memory \
  "p='$AUTO';s=open(p).read();o='    if (ncy) o.cycle = cy;';assert o in s;s=s.replace(o,'');open(p,'w').write(s)" \
  $UNIT

# ---- DORMANCY and INERTNESS ---------------------------------------------------------------------------------------
# ⛔ A CYCLE OF ONE IS A CYCLE. Since a member is eager inside its turn, a lone member's policy silently becomes
# `always` — and on PTR that is `reset:q`'s measured `gain>=2` replaced by the rule R2 measured reaching M16 NEVER,
# for the whole M15 → M21 stretch, with `reset:h` still locked.
mutant m12-a-cycle-of-one \
  "p='$AUTO';s=open(p).read();o='      var active2 = R.members.length >= 2;';assert o in s;s=s.replace(o,'      var active2 = R.members.length >= 1;');open(p,'w').write(s)" \
  $UNIT

# ⛔ INERTNESS: a cycle is derived for every row whether anything asked for it or not. Every reset in the game is
# suddenly scheduled, and the claim "everything new is OFF until a table or a player turns it on" is false.
mutant m13-a-cycle-on-every-row \
  "p='$AUTO';s=open(p).read();o='    for (var j = 0; j < order.length; j++) if (rows_on(by, order[j])) out.push(by[order[j]]);';s2='    for (var j = 0; j < order.length; j++) if (by[order[j]].on) out.push(by[order[j]]);';assert s2 in s;s=s.replace(s2,'    for (var j = 0; j < order.length; j++) out.push(by[order[j]]);');open(p,'w').write(s)" \
  $UNIT

# ---- DEMAND --------------------------------------------------------------------------------------------------------
# ⛔ DEMAND ONLY SPEAKS WHEN NOBODY HOLDS THE TURN. It then never moves anything — a member with a heavy weight holds
# the turn from the first tick and the layer something is waiting on never gets one. The two variants stop being
# distinguishable, which is the whole of Part 2.
mutant m14-demand-only-when-idle \
  "p='$AUTO';s=open(p).read();o='      if (C.demand) { var d = demandedMember(C, R); if (d && d.id !== C.holder)';assert o in s;s=s.replace(o,'      if (C.demand && !C.holder) { var d = demandedMember(C, R); if (d && d.id !== C.holder)');open(p,'w').write(s)" \
  $UNIT

# ⛔ A DEMAND SIGNAL IS "ANY VALUE THAT LOOKS LIKE A LAYER" rather than the one the CODE declares. The cycle then
# reads `yielding:native`'s layer, `waiting:stall-yield`'s layer and its OWN `waiting:turn` as demands — and the
# last of those feeds itself, so the holder demands its own turn for ever.
mutant m15-demand-is-any-layer-shaped-value \
  "p='$AUTO';s=open(p).read();o='      if (!last || !CODES[last.code] || !CODES[last.code].demand) continue;\n      var v = last.values && last.values[CODES[last.code].demand];\n      if (typeof v === %ss%s && v) want[v] = true;'.replace('%ss%s',chr(39)+'string'+chr(39));assert o in s;s=s.replace(o,'      if (!last || !last.values) continue;\n      for (var vk in last.values) { var v = last.values[vk]; if (typeof v === '+chr(39)+'string'+chr(39)+' && v && layers[v]) want[v] = true; }');open(p,'w').write(s)" \
  $UNIT

echo
echo "⛔ READ EVERY LINE ABOVE. A mutant that comes back GREEN is a gate that cannot see the defect it was written"
echo "   for, and the answer is a NEW ROW — not a note. R3a's round had two survivors on its first pass."

# ---- §34: the two defects the planner's ORACLE found, as mutants -----------------------------------------------
# ⛔ BOTH ARE THE BUILD THAT SHIPPED FOR AN AFTERNOON, and neither is visible to any stub leg — they need a REAL
# game over a WHOLE stretch, which is why `gates-r3b --part 7` exists. Each is checked against the ratio row.
#
# A HOLDER WHOSE OWN POLICY REFUSES YIELDS THE TURN. On PTR's `q` (`gain>=2`), Generator Power climbs back to where
# the ENGINE allows a reset while the gain is still one quirk — so a twenty-reset turn ends after ONE, every weight
# becomes the same run, and `reset:h=always` runs unscheduled. Measured: q 5 / h 37 against the oracle's 286 / 15.
mutant m16-yield-when-the-policy-refuses \
  "p='$AUTO';s=open(p).read();o='    if (!stallMod(P)) return d;';assert o in s;s=s.replace(o,'    if (turn) { var YC = cycleOf(f); if (YC && YC.holder === f.id) { endTurn(YC, f.id, %spreempted%s); } }\n    if (!stallMod(P)) return d;'.replace('%s',chr(39)));open(p,'w').write(s)" \
  $UNIT

# THE GUARD MEASURES FROM THE TURN'S START RATHER THAN THE HOLDER'S LAST ACT. A turn of weight W spans W resets, so
# the whole turn is compared against the usual wait for ONE — every weight above 1 is released mid-turn.
# ⚠ ⛔ THIS MUTANT IS **REDUNDANT AT THE SHIPPED DEFAULT**, and that is measured, not assumed — V4's second
# question, answered honestly. It comes back GREEN against `$UNIT` (on the stub a turn is spent inside a tick or two,
# so a bound from the turn's start is never reached) AND GREEN against `$RATIO` (0 RED, 3 green): with `K = 30` the
# bound is 30 × ~19 = ~570 game-seconds while a twenty-reset turn spans ~380, so BOTH clocks measure 19.1 and the
# two builds are indistinguishable. The clock-origin defect mattered at the INHERITED `K = 3`, and raising K to the
# measured 30 subsumed it.
# ⇒ What would separate them is a weight whose TURN SPAN exceeds `K × typical` — e.g. `turn@60` (~1140 s against a
# ~570 s bound), where the turn-start clock releases mid-turn and the act clock does not. That cell is the ROW a
# future slice should add to part 7 before trusting this mutant again. It is left here, RED-less and labelled, rather
# than deleted: the fix it protects is real and the reason it cannot currently fail is the interesting part.
# ⚠ It is a ~20-minute leg either way; the round is no longer a one-minute affair.
mutant m17-guard-clock-from-the-turn-start \
  "p='$AUTO';s=open(p).read();o='        var sinceAct = C.acted === null || C.acted === undefined ? C.since : C.acted;';assert o in s;s=s.replace(o,'        var sinceAct = C.since;');open(p,'w').write(s)" \
  $RATIO
