#!/usr/bin/env bash
# The R3b-2 mutant round — the DEAD-MEMBER RULE: a turn releases when its holder stops getting CLOSER.
#
# ⛔ FOR EVERY MUTANT, THE TWO QUESTIONS (V4's Part 5, kept):
#   1. CAN IT MOVE ITS ROW'S OWN REFERENCE? Every leg in `loader/cycle.test.mjs` judges the rule against the STUB's
#      own facts — the `state.can` flags and the `state.base` / `state.req` series the test itself drives, and the
#      act counts the stub records — never against `cycleState()` alone, which is a readout of the thing under test.
#      Where a leg does read `cycleState().skip` it ALSO asserts an act count, so a build that reported a release it
#      did not make still reds.
#   2. DOES A SECOND GUARD MAKE IT REDUNDANT? Named beside the ones where it does.
#
# ⛔ TWO MUTANTS ARE REDUNDANT AT THE SHIPPED DEFAULT, AND ONE EXPLANATION COVERS BOTH — the §34.5 discipline (a
# mutant that cannot fail is documented and labelled, not deleted and not reported as a pass). **`B` DEFAULTS TO 0,
# so the rule reads only whether the engine's fraction CHANGED — never by how much.** Every monotone reading of the
# same two engine quantities changes on exactly the same ticks, so any mutation that swaps ONE THRESHOLD FOR
# ANOTHER is invisible:
#   · `m-r3b2-normal-reads-nextat` (below) — survives, 0 RED, for that reason.
#   · `m-r3b2-static-reads-requires` — not written for the same reason, and it has a second one on top: the two
#     bars diverge only once the layer has RESET (a static layer's `nextAt` climbs, its `requires` does not), and
#     PTR's only static row-3 member is `ss`, which never resets at this frontier.
# ⇒ WHAT WOULD MAKE BOTH LIVE is a shipped `B > 0` (part 2 measures B = 0.1) or a stub leg with a `static` layer
# whose `nextAt` rises while its `requires` stands still. Recorded so the next slice inherits the gap rather than
# the illusion.
#
# ⛔ RESTORED FROM A COPY, NEVER FROM GIT — a harness that restores with `git checkout` restores over uncommitted
# work. The script refuses to start on a dirty tree.
#
# ⛔ DO NOT EDIT THIS FILE WHILE IT IS RUNNING. Bash reads a script incrementally, by byte offset.
#
#   bash tools/harness/mutants-r3b2.sh <out-dir> [name-filter]
set -uo pipefail
cd "$(dirname "$0")/../.."
OUT="${1:?usage: mutants-r3b2.sh <out-dir> [name-filter]}"
ONLY="${2:-}"
mkdir -p "$OUT"
if [ -n "$(git status --porcelain)" ]; then echo "REFUSING: the tree is dirty. Commit first — a mutant round restores over whatever is here."; exit 1; fi
AUTO=loader/tmt-auto.js
cp "$AUTO" "$OUT/tmt-auto.js.orig"
restore() { cp "$OUT/tmt-auto.js.orig" "$AUTO"; }
trap restore EXIT

mutant() {
  local name="$1" mut="$2"; shift 2
  if [ -n "$ONLY" ] && [[ "$name" != *"$ONLY"* ]]; then return 0; fi
  restore
  python3 -c "$mut" || { echo "$name: THE MUTATION DID NOT APPLY"; return 1; }
  echo "=== $name ==="
  git --no-pager diff --stat -- "$AUTO"
  "$@" > "$OUT/$name.log" 2>&1
  echo "$name: exit $? — $(grep -acE '^(RED|not ok)' "$OUT/$name.log") RED row(s), $(grep -acE '^(GREEN|ok )' "$OUT/$name.log") green"
  grep -aE '^(RED|not ok)' "$OUT/$name.log" | cut -c1-260
  restore
  git --no-pager diff --stat -- "$AUTO" | grep . && echo "!! NOT RESTORED" || echo "restored: diff is empty"
}

UNIT="node --test loader/cycle.test.mjs"
# The REAL-ENGINE half. `--part 1` on the L21 fixture is where the freeze itself lives, and it is short enough
# (4,000 ticks) to drive a mutant with. ONE run per cell: a mutant round asks whether a row REDDENS.
FREEZE="node tools/harness/gates-r3b2.mjs --part 1 --no-summary --no-write --repeat21 1 --pool 2 --ticks 1"

# ---- the rule fires at all -------------------------------------------------------------------------------------
# ⛔ THE DEFECT THIS SLICE EXISTS FOR, AS A MUTATION: the plateau branch removed, so a holder the engine refuses
# keeps the turn for ever. This is the state BEFORE the slice, and it is the freeze measured in §39.
# It must redden the stub's plateau leg AND the real-engine freeze row — two references, one defect.
mutant m-r3b2-a-refused-holder-is-never-released \
  "p='$AUTO';s=open(p).read();o='          if (hold > 0 && (now - C.closer) >= hold) endTurn(C, C.holder, \'released\');';assert o in s, 'anchor';s=s.replace(o,'          if (false) endTurn(C, C.holder, \'released\');');open(p,'w').write(s)" \
  $UNIT

# ⛔ AND THE OPPOSITE FAILURE, WHICH IS THE EXPENSIVE ONE: a holder that IS closing distance is released anyway —
# `h` starved, the state §32.1 item 2 measured at Hindrance Spirit ONE. The re-anchor never fires, so every refused
# holder loses its turn one window after it is granted.
# ⚠ THE REFERENCE IS THE CONSTRUCTED CLIMB, NOT THE MUTANT'S OWN HISTORY — the stub leg drives `state.base` itself.
mutant m-r3b2-a-climbing-holder-is-released \
  "p='$AUTO';s=open(p).read();o='    if (p - mark > need || p < mark) { C.mark[f.id] = p; C.closer = now; }';assert o in s, 'anchor';s=s.replace(o,'    if (false) { C.mark[f.id] = p; C.closer = now; }');open(p,'w').write(s)" \
  $UNIT

# ---- the anchor ---------------------------------------------------------------------------------------------------
# ⛔ A SIBLING'S WIPE COUNTED AS "NOT GETTING CLOSER". The brief asks this question out loud and the answer is NO:
# PTR's `h` loses base MID-TURN to row-2 spending it does not control (3.23e20 → 2.03e19 between two samples 25
# game-seconds apart, measured while `h` held the turn), and against a high-water that only ever rises those losses
# accumulate until the re-climb cannot beat it inside H. (A DROP lowering the mark is what this removes.)
mutant m-r3b2-wipe-costs-the-turn \
  "p='$AUTO';s=open(p).read();o='    if (p - mark > need || p < mark) { C.mark[f.id] = p; C.closer = now; }';assert o in s, 'anchor';s=s.replace(o,'    if (p - mark > need) { C.mark[f.id] = p; C.closer = now; }');open(p,'w').write(s)" \
  $UNIT

# ⛔ THE ANCHOR CLEARED WITH EVERY TURN — and this one SURVIVES, which is the round's most useful finding about the
# rule rather than about the gates. The intent was "the mark is a high-water that outlives a member's turns". IT IS
# NOT: a DROP lowers the mark (which is the wipe rule above, and it is load-bearing), and a dead member's base is
# wiped between its turns — so the mark is re-established from the wiped value on the first tick of the next turn
# whether it was carried over or not, and clearing it changes nothing. ⇒ the mark is the LAST ANCHOR, not a
# high-water, and the code now says so. The cost, named: a dead member pays its whole ~300 game-second climb again
# on every turn it is given rather than one window. The alternative (keep the high-water; let a drop restart only
# the CLOCK) would make this mutant live AND cost `o`/`ss` one `H` apiece — it is the first thing R3c should
# measure, and it is not taken here because it was not measured here.
mutant m-r3b2-mark-forgotten-each-turn \
  "p='$AUTO';s=open(p).read();o='    C.closer = C.since;';assert o in s, 'anchor';s=s.replace(o,'    C.closer = C.since; if (C.mark) delete C.mark[f.id];');open(p,'w').write(s)" \
  $FREEZE

# ---- which refusal the rule is about --------------------------------------------------------------------------
# ⛔ THE RULE LOOKING WHILE THE ENGINE WOULD ALLOW. §34.2 item 1: "my rule says not yet" is productive waiting and
# the weight exists to protect it — a member on `gain>=2` whose gain is momentarily 1 would lose its turn every
# window, which is the defect that made weight 5 and weight 20 the same run.
mutant m-r3b2-rule-ignores-the-engine \
  "p='$AUTO';s=open(p).read();o='        if (!engineAllows(h)) {';assert o in s, 'anchor';s=s.replace(o,'        if (true) {');open(p,'w').write(s)" \
  $UNIT

# ⛔ AND THE THRESHOLD READ OFF THE WRONG SIDE: `nextAt` for a NORMAL layer. `canReset` compares a normal layer's
# base against `requires`, and on PTR's `q` the two are different numbers — so the fraction would be measured
# against a bar the engine does not use, and a member could read "arrived" while the engine still refused it.
# ⚠ SURVIVES AT THE SHIPPED `B = 0`, for the reason in the header: the rule reads only whether the fraction
# CHANGED, and both readings change on the same ticks. Kept and labelled rather than deleted — the distinction it
# protects is real (it is V1 §16.3 item 8's trap) and it becomes live the moment `B > 0` ships.
mutant m-r3b2-normal-reads-nextat \
  "p='$AUTO';s=open(p).read();o=\"    var goal = t.type === 'static' ? t.nextAt : t.type === 'normal' ? t.requires : null;\";assert o in s, 'anchor';s=s.replace(o,\"    var goal = t.nextAt;\");open(p,'w').write(s)" \
  $FREEZE
