#!/usr/bin/env bash
# The U12 mutant round (docs/mobile.md, "The reset glow"). Each mutation (tools/harness/mutants-u12.py) breaks exactly
# ONE claim and must redden the check that exists for it — by NAME, out of gate M1's own JSON row (and, for the
# transparency mutant, gates-u12 --part 1's) — while leaving the others alone.
#
# ⛔ RESTORED FROM A COPY, NEVER FROM GIT (the U9 round's rule), and it refuses to start on a dirty tree.
# ⚠ `-uno`: in a WORKTREE `node_modules` is a SYMLINK and `.gitignore`'s `node_modules/` does not match one.
# ⛔ DO NOT EDIT THIS FILE WHILE IT IS RUNNING: bash reads a script by byte offset. The copy/restore block is ABOVE
# every mutant and nothing below it is a header — U11's first round was void because a header edit swallowed it.
#
#   bash tools/harness/mutants-u12.sh <out-dir> [name-filter]
#
# THE WITNESSES, by the one property each one brings:
#   · `ptr`               — one of the 13 engines with NO `resetTime` (the ones U11's sampler could not see a press
#                           on), and the one whose first two candidates (`b`, `g`: `tmp.canReset` true, the engine's
#                           own `canReset()` false) are pressed and MOVE NOTHING — so a call taken for a reset shows.
#   · `the-necromantree`  — also one of the 13, and its press (`n1`, row 2) touches three lower layers.
#   · `something`         — a `resetTime` engine whose press (`division`, row 3) zeroes lower layers' `resetTime`:
#                           the only kind of game where a wiped-layer glow can show itself.
#   · `the-yes-tree`      — a `resetTime` engine, row-0 press (the wiped half abstains there by construction).
# LEGS: trigger (the pressed layer lights, once, and is gone), repeat (a later reset of it lights again), wiped (no
# other card lights), rmotion (reduced motion: the hook saw it, nothing glowed), inert (gates-u12 --part 1).
# ⚠ An ABSTENTION reads as GREEN here, and every row prints its verdicts so an abstention is visible.
set -uo pipefail
cd "$(dirname "$0")/../.."
OUT="${1:?usage: mutants-u12.sh <out-dir> [name-filter]}"
ONLY="${2:-}"
mkdir -p "$OUT"
if [ -n "$(git status --porcelain -uno)" ]; then echo "REFUSING: tracked files are modified. Commit first — a mutant round restores over whatever is here."; exit 1; fi
FILES="loader/layerlist.js loader/layerlist.css"
for f in $FILES; do cp "$f" "$OUT/$(basename "$f").orig"; done
restore() { for f in $FILES; do cp "$OUT/$(basename "$f").orig" "$f"; done; }
trap restore EXIT

LEGS="trigger repeat wiped rmotion inert"

read_row() {   # $1 = game, $2 = "inert" to run the transparency part instead of M1
  if [ "${2:-}" = inert ]; then
    node tools/harness/gates-u12.mjs --part 1 "$1" --no-write 2>/dev/null | grep -a "^GREEN\|^RED" | grep -av VERDICT \
      | awk '{ ok = ($1 == "GREEN") ? "true" : "false"; sub(/^[A-Z]+ +/, ""); print "trigger=true repeat=true wiped=true rmotion=true inert=" ok " || " substr($0, 1, 400) }'
    return
  fi
  node tools/harness/page.mjs "$1" --gate mobile 2>/dev/null | node -e '
    let s = ""; process.stdin.on("data", (d) => { s += d; });
    process.stdin.on("end", () => {
      const line = s.split("\n").filter((l) => l.startsWith("{")).pop();
      if (!line) { console.log("PARSE=false"); return; }
      const d = JSON.parse(line), g = d.glow || {}, r = d.glowReduced || {};
      const o = { trigger: g.triggerOk !== false, repeat: g.repeatOk !== false, wiped: g.wipedOk !== false && r.wipedOk !== false, rmotion: r.triggerOk !== false, inert: true };
      console.log(Object.entries(o).map(([k, v]) => `${k}=${v === true}`).join(" ")
        + ` || glow: ${g.verdict} || reduced: ${r.verdict}${d.exception ? " || EXCEPTION " + d.exception : ""}`);
    });'
}

# $1 = name, $2.. = one `<game>=<leg>,<leg>` per game (`<game>=` for nothing red; `<game>@inert=` reads part 1).
mutant() {
  local name="$1"; shift
  local spec=("$@")
  if [ -n "$ONLY" ] && [[ "$name" != *"$ONLY"* ]]; then return 0; fi
  restore
  if [ "$name" != control ]; then python3 tools/harness/mutants-u12.py "$name" || { echo "$name: THE MUTATION DID NOT APPLY"; return 1; }; fi
  echo "=== $name  (expects: ${spec[*]:-nothing red})"
  git --no-pager diff --stat -- $FILES | tail -1
  local ok=1
  for e in "${spec[@]}"; do
    local g="${e%%=*}" want="${e#*=}" how=""
    if [[ "$g" == *@inert ]]; then g="${g%@inert}"; how=inert; fi
    want="${want//,/ }"
    local out; out="$(read_row "$g" "$how")"
    echo "  $g${how:+ (part 1)}: $out" | tee -a "$OUT/$name.log"
    local red=()
    for leg in $LEGS; do grep -q -- "$leg=true" <<<"$out" || red+=("$leg"); done
    local got="${red[*]:-}"
    if [ "$got" = "$want" ]; then echo "  OK   $g — red: [${got:-none}]"
    else echo "  FAIL $g — red: [${got:-none}], expected [${want:-none}]"; ok=0; fi
  done
  [ "$ok" = 1 ] && echo "  => $name OK" || echo "  => $name FAILED"
  restore
  git --no-pager diff --stat -- $FILES | grep . && echo "!! NOT RESTORED" || echo "  restored: diff is empty"
}

echo "control (no mutant):"
mutant control ptr= the-necromantree= something= the-yes-tree= ptr@inert=

# (1) THE HOOK REMOVED, U11's SAMPLER BACK — the build the user found dead. ⛔ It must redden the TRIGGER on the 13
#     (ptr, the-necromantree) and leave it GREEN on a `resetTime` engine, where U11's clock does see the press. On
#     `something` it also lights the wiped layers (U11 did; the user has ruled against it); and reduced motion
#     reddens everywhere, because the hook never saw the reset.
mutant m1-hook-removed-u11-sampler-back ptr=trigger,repeat,rmotion the-necromantree=trigger,repeat,rmotion something=wiped,rmotion the-yes-tree=rmotion

# (2) THE WIPED-LAYER GLOW REINSTATED (the hook for the pressed layer, U11's sampler for every other card): the
#     WIPED half reddens where a reset demonstrably zeroes lower clocks, and the trigger half stays green.
mutant m2-wiped-layers-glow something=wiped,rmotion the-yes-tree=

# (3) THE RESTART LIMIT WIDENED TO 10 s: the first reset still glows; the next one, after the glow ran out, does not.
mutant m3-rate-limit-10s ptr=repeat the-yes-tree=repeat

# (4) REDUCED MOTION'S JS GUARD REMOVED, the CSS rule kept: nothing animates (a visual check stays green) but the
#     list still counts and flips a glow — the reduced-motion leg's counters are what see it.
mutant m4-reduced-motion-js-guard-removed ptr=rmotion the-yes-tree=rmotion

# (5) A CALL TAKEN FOR A RESET (the rowReset "proceeded" mark ignored): ptr's first two candidates move nothing and
#     now glow anyway — "A LAYER THAT DID NOT RESET GLOWED".
mutant m5-glow-on-every-call ptr=wiped the-yes-tree=

# (6) THE WRAPPER NOT TRANSPARENT — the second argument dropped. Every M1 leg stays green (they press doReset(l)
#     with one argument); only the with/without comparison can see it.
mutant m6-wrapper-drops-force ptr@inert=inert ptr=
