#!/usr/bin/env bash
# The V6 + C1b mutant round — the Advanced toggles over ONE store (Q5), and the reader reading WORD-id buyables (Q8).
#
# ⛔ FOR EVERY MUTANT, THE TWO QUESTIONS (V4's Part 5, kept):
#   1. CAN IT MOVE ITS ROW'S OWN REFERENCE? gates-v6 judges each view against the OTHER view's rendering and against
#      `player.au.features` (neither is the component under test); part 2's reference feature is chosen through the
#      RUNTIME override, which does not read the saved map, so the stale-map mutant cannot move it — only the leg;
#      the freshness check judges the reader against the COMMITTED data, which a mutant of the reader cannot edit.
#   2. DOES A SECOND GUARD MAKE IT REDUNDANT? Named beside the ones where it does.
#
# ⛔ RESTORED FROM A COPY, NEVER FROM GIT — a harness that restores with `git checkout` restores over uncommitted
# work. The script refuses to start on a dirty tree. ⛔ DO NOT EDIT THIS FILE WHILE IT IS RUNNING (bash reads it by
# byte offset).
#
#   bash tools/harness/mutants-v6.sh <out-dir> [name-filter]
set -uo pipefail
cd "$(dirname "$0")/../.."
OUT="${1:?usage: mutants-v6.sh <out-dir> [name-filter]}"
ONLY="${2:-}"
mkdir -p "$OUT"
if [ -n "$(git status --porcelain)" ]; then echo "REFUSING: the tree is dirty. Commit first — a mutant round restores over whatever is here."; exit 1; fi
AUTO=loader/tmt-auto.js
PLAN=loader/tmt-planner.js
cp "$AUTO" "$OUT/tmt-auto.js.orig"
cp "$PLAN" "$OUT/tmt-planner.js.orig"
restore() { cp "$OUT/tmt-auto.js.orig" "$AUTO"; cp "$OUT/tmt-planner.js.orig" "$PLAN"; }
trap restore EXIT

mutant() {
  local name="$1" mut="$2"; shift 2
  if [ -n "$ONLY" ] && [[ "$name" != *"$ONLY"* ]]; then return 0; fi
  restore
  python3 -c "$mut" || { echo "$name: THE MUTATION DID NOT APPLY"; return 1; }
  echo "=== $name ==="
  git --no-pager diff --stat -- "$AUTO" "$PLAN"
  "$@" > "$OUT/$name.log" 2>&1
  echo "$name: exit $? — $(grep -cE '^(RED|STALE|not ok)' "$OUT/$name.log") RED row(s), $(grep -cE '^(GREEN|ok )' "$OUT/$name.log") green"
  grep -E '^(RED|STALE|not ok)' "$OUT/$name.log" | cut -c1-260
  restore
  git --no-pager diff --stat -- "$AUTO" "$PLAN" | grep . && echo "!! NOT RESTORED" || echo "restored: diff is empty"
}

G="node tools/harness/gates-v6.mjs --no-summary --no-write --part"

# ---- Q5 --------------------------------------------------------------------------------------------------------------
# ⛔ THE BRIEF'S OWN MUTANT: the Advanced toggle keeps ITS OWN COPY — seeded from the store on its first render, flipped
# locally on a press. A view SWITCH re-creates the component and re-seeds the copy, so the switch halves of part 1 can
# pass it; the leg that runs the GRID's onClick with Advanced still MOUNTED is the one that must red.
mutant m1-the-advanced-toggle-keeps-its-own-copy \
  "p='$AUTO';s=open(p).read();o='          return d.row.state === \'excluded\' ? null : T.toggleView(d.row.id);';assert o in s;s=s.replace(o,'          if (d.row.state === \'excluded\') return null; if (!this.copy) this.copy = T.toggleView(d.row.id); return Object.assign({}, this.copy);');o2='        press: function () { var r = T.pressFeature(this.data.row.id); this.refused = !r.ok;';assert o2 in s;s=s.replace(o2,'        press: function () { var r = T.pressFeature(this.data.row.id); if (r.ok && this.copy) { this.copy.saved = r.saved; this.copy.word = r.saved ? \'On\' : \'Off\'; } this.refused = !r.ok;');open(p,'w').write(s)" \
  $G 1

# ⛔ THE BRIEF'S OWN MUTANT: the toggle writes the save but `active()` reads a STALE map (a copy taken on its first
# call). Part 2 must red: the feature is pressed ON and still does nothing. Its reference cannot move — it switches
# the candidate on through the runtime override, which is a different branch of `active()`.
mutant m2-active-reads-a-stale-map \
  "p='$AUTO';s=open(p).read();o='    return isOnSaved(f) && featureUnlocked(f);\n  }';assert o in s;s=s.replace(o,'    if (!T._stale) T._stale = JSON.parse(JSON.stringify((player[AU] && player[AU].features) || {}));\n    return !!T._stale[f.id] && featureUnlocked(f);\n  }');open(p,'w').write(s)" \
  $G 2

# the Advanced press ignores `armable` — a locked feature is armed with the setting OFF. Part 4 must red.
mutant m3-the-advanced-press-ignores-armable \
  "p='$AUTO';s=open(p).read();o='    if (!armable(f)) return { ok: false, saved: isOnSaved(f), error: T.toggleView(id).why };';assert o in s;s=s.replace(o,'');open(p,'w').write(s)" \
  $G 4

# a DIFFERENT "All features" in the Advanced view: every UNLOCKED feature, ignoring U4's arming. With the setting off
# the two agree (part 1c cannot see it); part 4's master leg, with the setting ON, must red.
mutant m4-a-second-all-features \
  "p='$AUTO';s=open(p).read();o='    toggleAll();\n    return { ok: true, display: allDisplay() };';assert o in s;s=s.replace(o,'    var any = false; for (var i = 0; i < features.length; i++) if (!isOnSaved(features[i]) && featureUnlocked(features[i])) any = true;\n    for (var j = 0; j < features.length; j++) setIn(player[AU].features, features[j].id, any && featureUnlocked(features[j]));\n    return { ok: true, display: allDisplay() };');open(p,'w').write(s)" \
  $G 4

# the block does not say a RUNTIME override decides (only the profile is named). Part 5b must red, 5a must not.
mutant m5-the-runtime-override-is-not-named \
  "p='$AUTO';s=open(p).read();o='    if (enableOverride[f.id] !== undefined) return \'runtime\';\n    if (T.profileName === \'all\') return \'profile\';\n    return null;';assert o in s;s=s.replace(o,'    if (T.profileName === \'all\') return \'profile\';\n    return null;');open(p,'w').write(s)" \
  $G 5

# a press under a runtime override CLEARS it — the Advanced toggle stops matching the grid's press. Part 5b must red.
mutant m6-a-press-clears-the-runtime-override \
  "p='$AUTO';s=open(p).read();o='    toggleSaved(f);\n    return { ok: true, saved: isOnSaved(f), error: null };';assert o in s;s=s.replace(o,'    delete enableOverride[id];\n    toggleSaved(f);\n    return { ok: true, saved: isOnSaved(f), error: null };');open(p,'w').write(s)" \
  $G 5

# ⚠ EXPECTED TO SURVIVE, and the reason is a SECOND GUARD: the press does not invalidate the Advanced rows' cache.
# Every leg redraws with `updateTemp()`, and the header's display-text refreshes that cache inside it (V1's rule) —
# a real page does the same on its next interval. Recorded so a later reader knows the invalidation is belt AND braces.
mutant m7-no-invalidate-on-press \
  "p='$AUTO';s=open(p).read();o='    player[AU].disclosed = true;\n    invalidateView();\n  }\n  // ⚖ U4';assert o in s;s=s.replace(o,'    player[AU].disclosed = true;\n  }\n  // ⚖ U4');open(p,'w').write(s)" \
  $G 1

# ---- Q8 --------------------------------------------------------------------------------------------------------------
# ⛔ THE READER SKIPS WORD IDS AGAIN (the pre-C1b rule). The freshness check must red on a game with word-id buyables —
# the COMMITTED data holds the eight Lun4-R entries and the regenerated one does not. (The frozen C1-2 controls read
# the committed data and cannot see a reader mutant; freshness is the leg that can.)
mutant m8-the-reader-skips-word-ids-again \
  "p='$PLAN';s=open(p).read();o='filter(function (k) { return isBuyableDef(L.buyables[k]); });';assert o in s;s=s.replace(o,'filter(function (k) { return !isNaN(k) && isBuyableDef(L.buyables[k]); });');open(p,'w').write(s)" \
  node tools/currency-data.mjs --check --ids the-collab-tree-lun4-r,ptr

# the shape rule loosened: `null` / an array would be read as a buyable. No game has either under `buyables` today,
# so this is a CONSTRUCTED-only claim — EXPECTED TO SURVIVE freshness, recorded as the guard nothing on the roster needs.
mutant m9-the-shape-rule-admits-null \
  "p='$PLAN';s=open(p).read();o='function isBuyableDef(v) { return !!v && typeof v === \'object\' && !Array.isArray(v); }';assert o in s;s=s.replace(o,'function isBuyableDef(v) { return typeof v === \'object\'; }');open(p,'w').write(s)" \
  node tools/currency-data.mjs --check --ids the-collab-tree-lun4-r,ptr

echo "round done — logs in $OUT"
