#!/usr/bin/env bash
# The U8 mutant round (docs/mobile.md, "A resource row, once shown, STAYS shown"). Each mutation breaks exactly ONE
# claim and must redden the check that exists for it — by NAME, out of gate M1's own JSON row — while leaving the
# others alone. A mutant that reddens a check it cannot reach is the tell for a contaminated run, not a pass.
#
# ⛔ RESTORED FROM A COPY, NEVER FROM GIT. A harness that restores with `git checkout` restores over uncommitted
# work; this repo has lost mutants that way before. The copies are taken first, the tree is restored from them
# after every run, and the script refuses to start on a dirty tree.
#
# ⛔ DO NOT EDIT THIS FILE WHILE IT IS RUNNING: bash reads a script by byte offset and an edit mid-run resumes it
# in the middle of a word.
#
#   bash tools/harness/mutants-u8.sh <out-dir> [name-filter]
#
# ⚠ THE GAMES ARE CHOSEN, and each one is the only witness for something:
#   · `ptr`  — driven at its M16 snapshot, the one recorded state on the roster where a resource is attributed
#              UNAMBIGUOUSLY and a reset can take it away (`g.power` 1.96e555 → 0 under `doReset('sb', true)`).
#              It is the only game whose leg O does not abstain, so it is the only one that can score m1 and m4.
#   · `the-cultree`     — six keys (`k.sta`, `k.str`, `k.spd`, `k.int`, `k.wis`, `k.lck`) all print `1.00` and all
#              COLLIDE, so it is the witness for the collide filter (m2) and has none of ptr's attributions.
#   · `the-dressy-tree` — `Mi.clicky` claims `1` out of the prose where `format` prints `1.00`, which is the one
#              roster row that can tell the two formatters apart on a game leg O abstains on (m3).
set -uo pipefail
cd "$(dirname "$0")/../.."
OUT="${1:?usage: mutants-u8.sh <out-dir> [name-filter]}"
ONLY="${2:-}"
GAMES="${GAMES:-ptr the-cultree the-dressy-tree}"
mkdir -p "$OUT"
if [ -n "$(git status --porcelain)" ]; then echo "REFUSING: the tree is dirty. Commit first — a mutant round restores over whatever is here."; exit 1; fi
JS=loader/layerlist.js
cp "$JS" "$OUT/layerlist.js.orig"
restore() { cp "$OUT/layerlist.js.orig" "$JS"; }
trap restore EXIT

# The named checks, read out of gate M1's own JSON row (one line per game).
#   res            — the probe's own rebuild of the row set, the two ways onto a card, and the printed VALUE
#   stickyBefore   — leg O: the row WAS there while the resource was attributed
#   stickyAfter    — leg O: … and it is still there after the reset, printing the current value
#   resMem         — leg P: only unambiguous sightings are remembered, and the write goes to storage, not `player`
#   renderInert    — leg M (U7): a full render still writes nothing to `player`
# ⚠ stickyBefore and stickyAfter are read APART on purpose: m1 must redden the AFTER half and leave the BEFORE one
# green. A mutant that reddens both has been caught by the wrong assertion and says nothing about the row surviving.
LEGS="res stickyBefore stickyAfter resMem renderInert"

read_row() {  # read_row <game> → the five legs as "name=true|false"
  node tools/harness/page.mjs "$1" --gate mobile 2>/dev/null | node -e '
    let s = ""; process.stdin.on("data", (d) => { s += d; });
    process.stdin.on("end", () => {
      const line = s.split("\n").filter((l) => l.startsWith("{")).pop();
      if (!line) { console.log("PARSE=false"); return; }
      const d = JSON.parse(line);
      const L = (d.layers && d.layers.phone) || {};
      const o = { res: L.resOk && L.resMemKeyOk, stickyBefore: d.resStickyBeforeOk, stickyAfter: d.resStickyAfterOk,
        resMem: d.resMemOk, renderInert: d.renderInertOk };
      console.log(Object.entries(o).map(([k, v]) => `${k}=${v === true}`).join(" ")
        + ` || shown=${L.resShown} sticky=${L.resStickyRows} mem=${L.resMemKeys} withheld=${(L.resWithheld || []).length} restated=${(L.resRestated || []).length}`
        + ` || O: ${(d.resSticky || {}).verdict} || P: ${(d.resMem || {}).verdict} || ${JSON.stringify((L.resBad || []).slice(0, 1))}`);
    });'
}

# $1 = name, $2 = python mutation, $3.. = one `<game>=<leg>,<leg>` per game (an empty list is spelled `<game>=`).
#
# ⛔ THE EXPECTATION IS PER GAME, for the reason the U7 round records: two of these are invisible on a game that has
# no witness for them, and a single roster-wide expectation would have to be the weaker of the two and would stop
# saying which game actually witnessed the mutation.
mutant() {
  local name="$1" mut="$2"; shift 2
  local spec=("$@")
  if [ -n "$ONLY" ] && [[ "$name" != *"$ONLY"* ]]; then return 0; fi
  restore
  python3 -c "$mut" || { echo "$name: THE MUTATION DID NOT APPLY"; return 1; }
  echo "=== $name  (expects: ${spec[*]:-nothing red})"
  git --no-pager diff --stat -- "$JS" | tail -1
  local ok=1
  for g in $GAMES; do
    local want=""
    for e in "${spec[@]:-}"; do [ "${e%%=*}" = "$g" ] && want="${e#*=}"; done
    want="${want//,/ }"
    local out; out="$(read_row "$g")"
    echo "  $g: $out" | tee -a "$OUT/$name.log"
    local red=()
    for leg in $LEGS; do grep -q -- "$leg=true" <<<"$out" || red+=("$leg"); done
    local got="${red[*]:-}"
    if [ "$got" = "$want" ]; then echo "  OK   $g — red: [${got:-none}]"
    else echo "  FAIL $g — red: [${got:-none}], expected [${want:-none}]"; ok=0; fi
  done
  [ "$ok" = 1 ] && echo "  => $name OK" || echo "  => $name FAILED"
  restore
  git --no-pager diff --stat -- "$JS" | grep . && echo "!! NOT RESTORED" || echo "  restored: diff is empty"
}

echo "control (no mutant):"
mutant control "pass" ptr= the-cultree= the-dressy-tree=

# ---- the item itself -------------------------------------------------------------------------------------------
# (1) the stickiness dropped: a row exists only while the layer's text still states its value, which is the build
#     before U8. ⛔ It must redden the AFTER-reset half and NOT the before-reset one — the whole claim is that the
#     row was there and then survived.
mutant m1-stickiness-dropped \
  "p='loader/layerlist.js';s=open(p).read();o='      if (!has && !sticky[k]) return;';assert o in s;s=s.replace(o,'      if (!has) return;');open(p,'w').write(s)" \
  ptr=stickyAfter the-cultree= the-dressy-tree=

# (2) the collide filter dropped: an AMBIGUOUS attribution is made permanent too. ⚠ Only `the-cultree` can witness
#     it — `ptr` and `the-dressy-tree` have no colliding row at these states, which is what `withheld` reports.
mutant m2-collided-attribution-remembered \
  "p='loader/layerlist.js';s=open(p).read();o='      if (has && !collide) seenAdd(l, k);';assert o in s;s=s.replace(o,'      if (has) seenAdd(l, k);');open(p,'w').write(s)" \
  ptr= the-cultree=resMem the-dressy-tree=

# (3) the row prints `formatWhole` instead of `format` — decision 1 flipped. It can only redden a game with a row
#     in the one band where the two disagree (a non-zero value under 1,000).
mutant m3-row-prints-formatwhole \
  "p='loader/layerlist.js';s=open(p).read();o='  function resAmount(v) { return fmtNum(v, false); }';assert o in s;s=s.replace(o,'  function resAmount(v) { return fmtNum(v, true); }');open(p,'w').write(s)" \
  ptr= the-cultree=res the-dressy-tree=res

# (4) a remembered row prints the string it had WHEN IT WAS LAST ATTRIBUTED — the "frozen value" build, which is
#     the one a row that merely SURVIVES cannot distinguish itself from. The row is still there after the reset, so
#     only the VALUE check can see it.
#     ⚠ THE FIRST VERSION OF THIS MUTANT WAS VOID and the round said so: it skipped `syncResources`' write when the
#     element already had text, and a reset REBUILDS that element (the key set moves), so the guard never fired and
#     ptr came back green on every leg. The mutation has to live where the STRING is decided, not where it is
#     painted — so it caches the attributed string per (layer, key) and reuses it while the row is remembered.
mutant m4-remembered-row-freezes-its-string \
  "p='loader/layerlist.js';s=open(p).read();o='text: resAmount(v)';assert s.count(o) == 1;s=s.replace(o,'text: (has ? ((window.__u8frozen = window.__u8frozen || {})[l + \".\" + k] = resAmount(v)) : ((window.__u8frozen = window.__u8frozen || {})[l + \".\" + k] || resAmount(v)))');open(p,'w').write(s)" \
  ptr=stickyAfter the-cultree= the-dressy-tree=

# (5) the memory written into `player` instead of storage — decision 3 broken. ⚠ Leg M cannot see this at all: it
#     measures a render with the set ALREADY written, and a first-sight write does not happen there.
#     ⚠ AND THE HASH HALF OF LEG P COULD NOT SEE IT EITHER on two of the three games, which the first round
#     MEASURED: re-writing the same value into `player` moves no hash, so only `ptr` — whose set grows between the
#     first render and the leg — reddened. Leg P now compares the remembered set against the BYTES UNDER THE
#     STORAGE KEY, which needs no change to be visible. `the-cultree` remembers nothing (all six of its rows
#     collide), so it stores nothing either and genuinely cannot witness this one; the row says `0 remembered`.
mutant m5-memory-written-into-player \
  "p='loader/layerlist.js';s=open(p).read();o='      if (any) T.storage.raw.setItem.call(localStorage, k, JSON.stringify(o));';assert o in s;s=s.replace(o,'      if (any) player.uiLayerlistResources = JSON.stringify(o);');open(p,'w').write(s)" \
  ptr=resMem the-cultree= the-dressy-tree=resMem
