#!/usr/bin/env bash
# The C1 mutant round — the currency CONSUMERS, the READER's truth test, the schema, and the provenance gate.
#
# ⛔ FOR EVERY MUTANT, THE TWO QUESTIONS:
#   1. CAN IT MOVE ITS ROW'S OWN REFERENCE? The consumer rows judge against the stub's own `player.b.points` and
#      purchase counts (the loader cannot touch them); the reader rows judge a REGENERATION against the COMMITTED
#      data, which a mutant of the reader cannot rewrite; the schema rows judge against hand-built tables.
#   2. DOES A SECOND GUARD MAKE IT REDUNDANT? Named beside the ones where it does — and those are REPORTED as such,
#      not counted as kills.
#
# ⛔ RESTORED FROM A COPY, NEVER FROM GIT — the script refuses to start on a dirty tree. ⛔ DO NOT EDIT THIS FILE
# WHILE IT IS RUNNING (bash reads it by byte offset).
#
#   bash tools/harness/mutants-c1.sh <out-dir> [name-filter]
set -uo pipefail
cd "$(dirname "$0")/../.."
OUT="${1:?usage: mutants-c1.sh <out-dir> [name-filter]}"
ONLY="${2:-}"
mkdir -p "$OUT"
if [ -n "$(git status --porcelain)" ]; then echo "REFUSING: the tree is dirty. Commit first — a mutant round restores over whatever is here."; exit 1; fi
FILES="loader/tmt-auto.js loader/tmt-planner.js loader/page.js tools/auto-tables.mjs"
for f in $FILES; do cp "$f" "$OUT/$(basename "$f").orig"; done
restore() { for f in $FILES; do cp "$OUT/$(basename "$f").orig" "$f"; done; }
trap restore EXIT

mutant() {
  local name="$1" mut="$2"; shift 2
  if [ -n "$ONLY" ] && [[ "$name" != *"$ONLY"* ]]; then return 0; fi
  restore
  python3 -c "$mut" || { echo "$name: THE MUTATION DID NOT APPLY"; return 1; }
  echo "=== $name ==="
  git --no-pager diff --stat -- $FILES
  "$@" > "$OUT/$name.log" 2>&1
  echo "$name: exit $? — $(grep -cE '^(RED|not ok|STALE)' "$OUT/$name.log") RED row(s), $(grep -cE '^(GREEN|ok )' "$OUT/$name.log") green"
  grep -E '^(RED|not ok|STALE)' "$OUT/$name.log" | cut -c1-240
  restore
  git --no-pager diff --stat -- $FILES | grep . && echo "!! NOT RESTORED" || echo "restored: diff is empty"
}

UNIT="node --test loader/currency.test.mjs loader/auto-tables.test.mjs"
CHECK="node tools/currency-data.mjs --check --jobs 6"
G1="node tools/harness/page.mjs ptr --gate load"

# ---- the CONSUMERS -----------------------------------------------------------------------------------------------
# the brief's own defect: the reserve reads the layer's OWN points whatever the data says
mutant m1-the-reserve-reads-own-points \
  "p='loader/tmt-auto.js';s=open(p).read();o='var path = paysIn(l, id) || ownPath, lm'; assert o in s; s=s.replace(o,'var path = ownPath, lm'); open(p,'w').write(s)" \
  $UNIT
# an UNSCORED entry promoted to an answer — the regex's pick shipped as fact
mutant m2-an-unscored-entry-is-an-answer \
  "p='loader/tmt-auto.js';s=open(p).read();o=\"return e && e.scored === true && typeof e.pays === 'string' ? e.pays : null;\"; assert o in s; s=s.replace(o,\"return e && typeof e.pays === 'string' ? e.pays : null;\"); open(p,'w').write(s)" \
  $UNIT
# the foreign branch never engages (the reader's answer read and then ignored)
mutant m3-the-foreign-branch-never-engages \
  "p='loader/tmt-auto.js';s=open(p).read();o='if (pp && pp !== ownPath) { foreign = true; break; }'; assert o in s; s=s.replace(o,'if (false) { foreign = true; break; }'); open(p,'w').write(s)" \
  $UNIT
# the refusal guesses the layer's own points instead of saying "unknown"
mutant m4-an-unknown-currency-is-guessed \
  "p='loader/tmt-auto.js';s=open(p).read();o='var cur = paysIn(l, minId);'; assert o in s; s=s.replace(o,\"var cur = paysIn(l, minId) || ('player.' + l + '.points');\"); open(p,'w').write(s)" \
  $UNIT

# ---- the SCHEMA and the PROVENANCE gate ---------------------------------------------------------------------------
# the loader's version check gone. ⚠ SECOND GUARD: the schema's `enum` on formatVersion still refuses version 2 — so
# this mutant can only red the row that asserts the loader's OWN sentence; the refusal itself survives.
mutant m5-the-loader-reads-any-version \
  "p='loader/tmt-auto.js';s=open(p).read();o=\"      if (TABLE_FORMAT_VERSIONS.indexOf(table.formatVersion) < 0) throw\"; assert o in s; s=s.replace(o,\"      if (false) throw\"); open(p,'w').write(s)" \
  $UNIT
# a table with no version accepted
mutant m6-a-table-without-a-version-loads \
  "p='loader/tmt-auto.js';s=open(p).read();o=\"      if (table.formatVersion === undefined) throw\"; assert o in s; s=s.replace(o,\"      if (false) throw\"); open(p,'w').write(s)" \
  $UNIT
# the ancestry check gone
mutant m7-a-commit-that-is-not-an-ancestor-passes \
  "p='tools/auto-tables.mjs';s=open(p).read();o='if (!ancestor(r.commit)) bad.push'; assert o in s; s=s.replace(o,'if (false) bad.push'); open(p,'w').write(s)" \
  $UNIT
# the missing-record check gone
mutant m8-a-missing-record-passes \
  "p='tools/auto-tables.mjs';s=open(p).read();o='const missing = [...need].filter((k) => !prov[k]).sort();'; assert o in s; s=s.replace(o,'const missing = [];'); open(p,'w').write(s)" \
  $UNIT
# a gate id that no SUMMARY row carries passes
mutant m9-an-unknown-gate-id-passes \
  "p='tools/auto-tables.mjs';s=open(p).read();o='if (!r.run && !gateInSummary(r.gate, labels)) bad.push'; assert o in s; s=s.replace(o,'if (false) bad.push'); open(p,'w').write(s)" \
  $UNIT

# ---- the READER'S TRUTH -------------------------------------------------------------------------------------------
# ⛔ THE DEFECT THE BRIEF NAMES: "a field that fell" instead of "the field that fell BY THE COST". Caught by the
# regeneration against the COMMITTED data (the mutant cannot rewrite what is committed).
mutant m10-any-fall-is-the-currency \
  "p='loader/tmt-planner.js';s=open(p).read();o='      })) exact.push(p);'; assert o in s; s=s.replace(o,'      }) || true) exact.push(p);'); open(p,'w').write(s)" \
  $CHECK
# the second decrement pattern gone (the alias) — moves six picks
mutant m11-no-alias-pattern \
  "p='loader/tmt-planner.js';s=open(p).read();o='    aliases.forEach(function (a) {'; assert o in s; s=s.replace(o,'    aliases = [];\n    aliases.forEach(function (a) {'); open(p,'w').write(s)" \
  $CHECK

# ---- the PAGE -----------------------------------------------------------------------------------------------------
# the PLAIN page fetches the generated data too (the opt-in lost)
mutant m12-the-plain-page-fetches-games-data \
  "p='loader/page.js';s=open(p).read();o=\"  if (AUTOMATION) {\n    // ---- the GENERATED currency data\"; assert o in s; s=s.replace(o,\"  if (true) {\n    // ---- the GENERATED currency data\"); open(p,'w').write(s)" \
  $G1
