#!/usr/bin/env bash
# The U7 mutant round (docs/mobile.md, "U7"). Each mutation breaks exactly ONE of the three items and must redden
# the check that exists for it — by NAME, out of gate M1's own JSON row — while leaving the others alone. A mutant
# that reddens a check it cannot reach is the tell for a contaminated run, not a pass.
#
# ⛔ RESTORED FROM A COPY, NEVER FROM GIT. A harness that restores with `git checkout` restores over uncommitted
# work; this repo has lost mutants that way before. The copies are taken first, the tree is restored from them
# after every run, and the script refuses to start on a dirty tree — because a dirty tree is exactly the case
# where the copy is the only thing standing between the mutation and the work.
#
# ⛔ DO NOT EDIT THIS FILE WHILE IT IS RUNNING: bash reads a script by byte offset and an edit mid-run resumes it
# in the middle of a word.
#
#   bash tools/harness/mutants-u7.sh <out-dir> [name-filter]
#
# ⚠ THE GAMES ARE CHOSEN, not defaulted. `ptr` is driven at its M16 snapshot, which is the only recorded state on
# the roster that renders an EMPTY second reset line (`p` and `e`, both `normal` past `resetGain` 100) — the half
# of item 1 that a static-only check cannot see — and the only one with a non-degenerate other-resource
# (`t.energy`, `q.energy`). `the-yes-tree` is there for item 3: it is the sample that HAS layers where the cheapest
# unearned upgrade is not the first-listed one, which is what makes the cheapest-vs-first mutant non-vacuous.
set -uo pipefail
cd "$(dirname "$0")/../.."
OUT="${1:?usage: mutants-u7.sh <out-dir> [name-filter]}"
ONLY="${2:-}"
GAMES="${GAMES:-ptr the-yes-tree}"
mkdir -p "$OUT"
if [ -n "$(git status --porcelain)" ]; then echo "REFUSING: the tree is dirty. Commit first — a mutant round restores over whatever is here."; exit 1; fi
JS=loader/layerlist.js
CSS=loader/layerlist.css
cp "$JS" "$OUT/layerlist.js.orig"
cp "$CSS" "$OUT/layerlist.css.orig"
restore() { cp "$OUT/layerlist.js.orig" "$JS"; cp "$OUT/layerlist.css.orig" "$CSS"; }
trap restore EXIT

# The named checks, read out of gate M1's own JSON row (one line per game).
#   resetSplit   — the button really is two line elements holding the engine's own split, each one line box tall
#   resetHeight  — leg L: the block's height over the GROWN and the FLIPPED string, on the same card
#   res          — the other-resource filter, against the probe's own occurrence budget, in both directions
#   prog         — the progress rows against the probe's own fourth rebuild
#   multiRes     — leg N: a constructed cost in several currencies is skipped, counted and not rendered
#   renderInert  — a full render still writes nothing to `player`
LEGS="resetSplit resetHeight res prog multiRes renderInert"

read_row() {  # read_row <game> → the six legs as "name=true|false"
  node tools/harness/page.mjs "$1" --gate mobile 2>/dev/null | node -e '
    let s = ""; process.stdin.on("data", (d) => { s += d; });
    process.stdin.on("end", () => {
      const line = s.split("\n").filter((l) => l.startsWith("{")).pop();
      if (!line) { console.log("PARSE=false"); return; }
      const d = JSON.parse(line);
      const L = (d.layers && d.layers.phone) || {};
      const o = { resetSplit: L.resetOk, resetHeight: d.resetHeightOk, res: L.resOk, prog: L.progOk,
        multiRes: d.multiResOk, renderInert: d.renderInertOk };
      console.log(Object.entries(o).map(([k, v]) => `${k}=${v === true}`).join(" ")
        + ` || witnesses cheapest=${L.cheapestWitnesses} emptyL2=${(d.resetHeight || {}).emptyL2} resShown=${L.resShown}`
        + ` || ${((d.resetHeight || {}).bad || []).slice(0, 2).join(" ; ")} ${JSON.stringify((L.resBad || []).slice(0, 1))} ${JSON.stringify((L.progBad || []).slice(0, 1))}`);
    });'
}

# $1 = name, $2 = python mutation, $3.. = the legs whose RED is the claim (per game, ALL games must show it)
mutant() {
  local name="$1" mut="$2"; shift 2
  local want="$*"
  if [ -n "$ONLY" ] && [[ "$name" != *"$ONLY"* ]]; then return 0; fi
  restore
  python3 -c "$mut" || { echo "$name: THE MUTATION DID NOT APPLY"; return 1; }
  echo "=== $name  (expects red: [${want:-none}])"
  git --no-pager diff --stat -- "$JS" "$CSS" | tail -1
  local ok=1
  for g in $GAMES; do
    local out; out="$(read_row "$g")"
    echo "  $g: $out" | tee -a "$OUT/$name.log"
    local red=()
    for leg in $LEGS; do grep -q -- "$leg=true" <<<"$out" || red+=("$leg"); done
    local got="${red[*]:-}"
    if [ "$got" = "$want" ]; then echo "  OK   $g — red: [${got:-none}]"
    else echo "  FAIL $g — red: [${got:-none}], expected [${want:-none}]"; ok=0; fi
  done
  [ "$ok" = 1 ] && echo "  => $name OK" || echo "  => $name FAILED"
  restore
  git --no-pager diff --stat -- "$JS" "$CSS" | grep . && echo "!! NOT RESTORED" || echo "  restored: diff is empty"
}

echo "control (no mutant):"
mutant control "pass"

# ---- item 1 ----------------------------------------------------------------------------------------------------
# (a) the split reverted to what shipped before U7: one run of text, the engines' `<br>`s collapsed to spaces.
#     Both item-1 checks must red — the probe's, because there are no line elements at all, and leg L's, because a
#     single run's height answers to how many characters are in it.
mutant m1-split-reverted-to-space-collapse \
  "p='loader/layerlist.js';s=open(p).read();o='        var rl = resetLines(resetText(l));\n        c.resetL1.innerHTML = rl[0];\n        c.resetL2.innerHTML = rl[1];';assert o in s;s=s.replace(o,'        c.reset.innerHTML = resetText(l).replace(/<br\\\\s*\\\\/?>/gi, \\\" \\\");');open(p,'w').write(s)" \
  resetSplit resetHeight

# (b) the two-line height made CONDITIONAL on the second line being non-empty — the `normal`-type half.
#     ⛔ THE POINT OF THIS MUTANT: a check that only ever exercised a `static` layer stays GREEN under it, because
#     a static layer's second half is there. It reddens on the cards whose second half the engine did NOT emit,
#     which on `ptr` at M16 are `p` and `e`. On a game with none of those it is expected to stay green, and the
#     leg's `emptyL2` list is what says whether the game could judge it — which is why `ptr` is in GAMES.
mutant m2-two-line-height-conditional \
  "p='loader/layerlist.css';s=open(p).read();o='#tmt-layerlist .tmt-layerlist-resetline {';assert o in s;s=s.replace(o,'#tmt-layerlist .tmt-layerlist-resetline[data-line=\\\"2\\\"]:empty { min-height: 0; }\n'+o);open(p,'w').write(s)" \
  resetSplit resetHeight

# ---- item 2 ----------------------------------------------------------------------------------------------------
# the filter dropped: every candidate Decimal renders, bookkeeping included
mutant m3-resource-filter-dropped \
  "p='loader/layerlist.js';s=open(p).read();o='      var shown = takeOccurrence(text, budget, v);\n      if (shown === null) return;';assert o in s;s=s.replace(o,'      var shown = takeOccurrence(text, budget, v);\n      if (shown === null) shown = whole(v);');open(p,'w').write(s)" \
  res

# ---- item 3 ----------------------------------------------------------------------------------------------------
# cheapest replaced by first-listed EVERYWHERE. ⚠ It can only redden a sample that HAS a category where the two
# rules pick different components; `cheapestWitnesses` in the row above is what says whether this one did.
mutant m4-cheapest-becomes-first-listed \
  "p='loader/layerlist.js';s=open(p).read();o='      if (same) g.cand.forEach(function (c) { if (ltAmt(c.target, one.target)) one = c; });';assert o in s;s=s.replace(o,'      /* mutant: first-listed everywhere */');open(p,'w').write(s)" \
  prog

# a cost in SEVERAL currencies rendered instead of skipped: its first entry's cost becomes the target
mutant m5-multires-rendered-not-skipped \
  "p='loader/layerlist.js';s=open(p).read();o='        if (part.multi && numFieldOf(part.multi, decl, t)) g.skipped++;\n        return;';assert o in s;s=s.replace(o,'        var m = part.multi ? numFieldOf(part.multi, decl, t) : null;\n        if (!m || typeof m.length !== \\\"number\\\" || !m.length) return;\n        v = safe(function () { return m[0].cost; }, undefined);\n        if (!isAmount(v)) return;');open(p,'w').write(s)" \
  multiRes
