#!/usr/bin/env bash
# The V4 mutant round — the per-feature CONTROLS (`while`, `until`, `priority`) and V4b's RESET.
#
# ⛔ FOR EVERY MUTANT, TWO QUESTIONS WERE ASKED BEFORE IT WAS WRITTEN (the brief's Part 5):
#   1. CAN IT MOVE ITS LEG'S OWN REFERENCE? Every leg here is PAIRED against a control that has NOTHING set — no
#      `while`, no `until`, no `priority` — and every mutation below is inside a branch that only a set control can
#      reach. So the reference is out of the mutant's reach by construction, not by luck. The one that is not is
#      m4 (`priority` ignored), whose control also runs through `layerOrder`; its reference is therefore the
#      CONTROL RUN's own purchases, taken in a process the mutation is not applied to (the unit file boots twice).
#   2. DOES A SECOND GUARD MAKE IT REDUNDANT? Named beside each one where it does, and the redundant ones are not
#      here. ⚠ A mutant that only changes a LABEL is excluded on purpose: `blocked:gate`'s `owner` is asserted twice
#      (the vocabulary table in `gates-v4 --part 1`, and the value on a real decision in the unit file), so a
#      mutation that drops it would red two rows and prove nothing about the mechanism.
#
# ⛔ RESTORED FROM A COPY, NEVER FROM GIT — a harness that restores with `git checkout` restores over uncommitted
# work. The copy is taken first, the tree is restored after every run, and the script refuses to start on a dirty
# tree, because a dirty tree is the case where the copy is the only thing between the mutation and the work.
#
# ⛔ DO NOT EDIT THIS FILE WHILE IT IS RUNNING. Bash reads a script incrementally, by byte offset.
#
#   bash tools/harness/mutants-v4.sh <out-dir> [name-filter]
set -uo pipefail
cd "$(dirname "$0")/../.."
OUT="${1:?usage: mutants-v4.sh <out-dir> [name-filter]}"
ONLY="${2:-}"
mkdir -p "$OUT"
if [ -n "$(git status --porcelain)" ]; then echo "REFUSING: the tree is dirty. Commit first — a mutant round restores over whatever is here."; exit 1; fi
AUTO=loader/tmt-auto.js
cp "$AUTO" "$OUT/tmt-auto.js.orig"
restore() { cp "$OUT/tmt-auto.js.orig" "$AUTO"; }
trap restore EXIT

mutant() {
  local name="$1" mut="$2"; shift 2
  if [ -n "$ONLY" ] && [[ "$name" != *"$ONLY"* ]]; then return 0; fi
  restore
  python3 -c "$mut" || { echo "$name: THE MUTATION DID NOT APPLY"; return 1; }
  echo "=== $name ==="
  git --no-pager diff --stat -- "$AUTO"
  "$@" > "$OUT/$name.log" 2>&1
  echo "$name: exit $? — $(grep -cE '^(RED|not ok)' "$OUT/$name.log") RED row(s), $(grep -cE '^(GREEN|ok )' "$OUT/$name.log") green"
  grep -E '^(RED|not ok)' "$OUT/$name.log" | cut -c1-260
  restore
  git --no-pager diff --stat -- "$AUTO" | grep . && echo "!! NOT RESTORED" || echo "restored: diff is empty"
}

UNIT="node --test loader/controls.test.mjs"
V4="node tools/harness/gates-v4.mjs --no-summary"

# ---- `while`: the PAUSE ------------------------------------------------------------------------------------------
# ⛔ THE ONE THE BRIEF NAMES. "`while` is evaluated once and cached" is not a strawman: the compiled FUNCTION is
# cached against its source (which is right), and caching its ANSWER beside it is one line away. It reds the row
# whose predicate changes mid-leg, and a build with it would be green on every static predicate there is.
mutant m1-while-answer-cached \
  "p='$AUTO';s=open(p).read();o='    var v = evalPredicate(c);\n    if (v.error) return { code: \'blocked:predicate\', values: { which: \'while\', src: c.src } };\n    if (v.value) return null;';assert o in s;s=s.replace(o,'    if (c.cachedAnswer === undefined) c.cachedAnswer = evalPredicate(c);\n    var v = c.cachedAnswer;\n    if (v.error) return { code: \'blocked:predicate\', values: { which: \'while\', src: c.src } };\n    if (v.value) return null;');open(p,'w').write(s)" \
  $UNIT

# A RUN-TIME THROW READS AS `false`. ⚠ This is the mutation the code exists to prevent and it is INVISIBLE to any
# row that only asks "did the feature act?" — a throwing gate and a false gate both stop it. The leg that sees it
# asks for the CODE and for the other feature's action on the same tick.
mutant m2-a-throw-reads-as-false \
  "p='$AUTO';s=open(p).read();o='    try { return { value: !!c.fn(), error: null }; } catch (e) { return { value: null, error: String((e && e.message) || e) }; }';assert o in s;s=s.replace(o,'    try { return { value: !!c.fn(), error: null }; } catch (e) { return { value: false, error: null }; }');open(p,'w').write(s)" \
  $UNIT

# AN EMPTY SAVED VALUE FALLS THROUGH TO THE TABLE. `null` = not set, `''` = set to NONE: collapse the two and a
# player can no longer remove a gate their game's table ships, which is the only way PTR's own M21 pause is optional.
mutant m3-empty-saved-value-falls-through \
  "p='$AUTO';s=open(p).read();o='    if (v === undefined || v === null) return null;\n    // ⚠ A SAVE THIS BUILD CANNOT VALIDATE IS IGNORED, NOT RUN';assert o in s;s=s.replace(o,'    if (v === undefined || v === null || v === \'\') return null;\n    // ⚠ A SAVE THIS BUILD CANNOT VALIDATE IS IGNORED, NOT RUN');open(p,'w').write(s)" \
  $UNIT

# ---- `until`: the LATCH ------------------------------------------------------------------------------------------
# ⛔ "until behaves like while" — the whole difference between the two controls, and the row that sees it needs a
# NON-MONOTONE predicate (R2 measured that PTR's own M16 predicate is one, so this is not a contrived shape).
mutant m4-until-does-not-latch \
  "p='$AUTO';s=open(p).read();o='    if (hit !== null) {';assert o in s;s=s.replace(o,'    if (false) {');open(p,'w').write(s)" \
  $UNIT

# ⛔ "the latch is not saved" — it goes into a module-level map instead, which is invisible to a reload and is
# EXACTLY what the brief said to decide by measurement. ⚠ The unit file's row for this asserts `player.au.edits`
# directly; the page and the headless resume are the other two witnesses, and they are not redundant with it —
# this one says WHERE it is, they say that a new process can find it.
mutant m5-latch-in-runtime-memory \
  "p='$AUTO';s=open(p).read();o='    var now = Math.round((Number(player.timePlayed) || 0) * 10) / 10;\n    writeEdit(f.id, \'untilHit\', now);';assert o in s;s=s.replace(o,'    var now = Math.round((Number(player.timePlayed) || 0) * 10) / 10;\n    (globalThis.__mutLatch || (globalThis.__mutLatch = {}))[f.id] = now;');t='  function untilHitOf(f) {\n    var e = editsOf(), v = e && e[f.id] ? e[f.id].untilHit : undefined;';assert t in s;s=s.replace(t,'  function untilHitOf(f) {\n    var e = { }, v = (globalThis.__mutLatch || {})[f.id];');open(p,'w').write(s)" \
  $UNIT

# `until` checked AFTER `while`: a stopped feature then reports its gate instead of its stop.
mutant m6-until-after-while \
  "p='$AUTO';s=open(p).read();o='      var stop = untilStep(f);\n      if (stop) { say(f, stop.code, stop.values); continue; }\n      var pause = whileStep(f);\n      if (pause) { say(f, pause.code, pause.values); continue; }';assert o in s;s=s.replace(o,'      var pause = whileStep(f);\n      if (pause) { say(f, pause.code, pause.values); continue; }\n      var stop = untilStep(f);\n      if (stop) { say(f, stop.code, stop.values); continue; }');open(p,'w').write(s)" \
  $UNIT

# ---- `priority` ---------------------------------------------------------------------------------------------------
# ⛔ "priority ignored". ⚠ ITS LEG'S REFERENCE IS THE CONTROL BOOT, taken in the same process but from a SECOND
# `bootStub`, so the mutation applies to both — which is exactly why the row asserts what each feature BOUGHT under
# the EDITED arm against a fixed expectation (`buyables[11] === 2`, `upgrades === []`) rather than "the two differ".
mutant m7-priority-ignored \
  "p='$AUTO';s=open(p).read();o='    if (!moved) return (orderCache[l] = base);';assert o in s;s=s.replace(o,'    if (true) return (orderCache[l] = base);');open(p,'w').write(s)" \
  $UNIT

# THE DEFAULT IS A LITERAL rather than the kind's own place. A build with this is byte-identical on ptr (whose
# kindOrder puts reset second) until somebody edits ONE feature — and then everything else jumps ahead of it.
mutant m8-default-priority-is-a-literal \
  "p='$AUTO';s=open(p).read();o='  function priorityOf(f) { var p = controlOf(f, \'priority\'); return p === null || p === undefined ? f.kindIndex : p; }';assert o in s;s=s.replace(o,'  function priorityOf(f) { var p = controlOf(f, \'priority\'); return p === null || p === undefined ? 1 : p; }');open(p,'w').write(s)" \
  $UNIT

# ---- the guards a typed value goes through ------------------------------------------------------------------------
# A PREDICATE IS COMMITTED BEFORE IT IS COMPILED. ⚠ Aimed at the GUARD, not at the message (V2 m5's lesson): with
# the check gone the text really is written, and the next tick's `predicateOf` cannot compile it — so the feature
# blocks on a value the player was told was accepted.
mutant m9-refused-predicate-reaches-the-save \
  "p='$AUTO';s=open(p).read();o='    var why = checkParam(CONTROL_ROW, name, v);\n    if (why) return { ok: false, value: controlOf(f, name), error: why };\n    var was = controlOf(f, name);';assert o in s;s=s.replace(o,'    var why = null;\n    if (why) return { ok: false, value: controlOf(f, name), error: why };\n    var was = controlOf(f, name);');open(p,'w').write(s)" \
  $UNIT

# A SAVED VALUE THIS BUILD CANNOT VALIDATE IS RUN — the hand-edited / later-version save, and V2's own rule for a
# saved policy applied to a predicate, where it matters more because the value is `new Function`'d.
mutant m10-unvalidatable-save-is-run \
  "p='$AUTO';s=open(p).read();o='    if (checkParam(CONTROL_ROW, name, v)) return null;\n    return name === \'priority\' ? Math.round(Number(v)) : String(v);';assert o in s;s=s.replace(o,'    return name === \'priority\' ? Math.round(Number(v)) : String(v);');open(p,'w').write(s)" \
  $UNIT

# THE PREDICATE IS NOT ESCAPED in the block it is rendered into. `display-text` is `v-html` on both engines.
mutant m11-predicate-not-escaped \
  "p='$AUTO';s=open(p).read();o=\"o.push('<div style=\\\"text-align:left;font-size:.9em;opacity:.85\\\">acts only while <code>' + esc(ctl['while'].value)\";assert o in s;s=s.replace(o,\"o.push('<div style=\\\"text-align:left;font-size:.9em;opacity:.85\\\">acts only while <code>' + (ctl['while'].value)\");open(p,'w').write(s)" \
  $UNIT

# ---- V4b: the RESET ------------------------------------------------------------------------------------------------
# ⛔ THE ONE THE SPEC NAMES: a reset that clears the SAVE and leaves the memory outside it. A feature the stall watch
# has escalated, or one a `setPolicy` override is driving, then goes on running a policy nothing on screen names —
# the settings read as reset and the game does not behave as if they were.
mutant m12-reset-leaves-the-runtime \
  "p='$AUTO';s=open(p).read();o='    cleared.runtimeEnabled = T.clearFeatureOverrides();';assert o in s;s=s.replace(o,'    cleared.runtimeEnabled = 0;');t='      if (f.policyRuntime !== null) { cleared.runtimePolicies++; f.policyRuntime = null; }';assert t in s;s=s.replace(t,'      if (f.policyRuntime !== null) { cleared.runtimePolicies++; }');open(p,'w').write(s)" \
  $UNIT

# THE RESERVED ENTRY IS MISSED. `edits['*']` is the stall watch's own settings; it is found by a KEY WALK and by
# nothing else, because every other reader looks a feature up BY ID. A reset written the obvious way — over the
# feature list — leaves it, and the watch comes back on.
mutant m13-reset-misses-the-reserved-entry \
  "p='$AUTO';s=open(p).read();o=\"    if (e) for (k in e) { cleared.edits++; delIn(e, k); }\";assert o in s;s=s.replace(o,\"    if (e) for (var bi = 0; bi < features.length; bi++) if (e[features[bi].id]) { cleared.edits++; delIn(e, features[bi].id); }\");open(p,'w').write(s)" \
  $UNIT

# `features` SET FALSE RATHER THAN DELETED. A map of explicit `false`s behaves identically and is a DIFFERENT object,
# so only a row that compares against a FRESH BOOT can see it — which is exactly why the spec is a deep-equal.
mutant m14-reset-sets-false-instead-of-deleting \
  "p='$AUTO';s=open(p).read();o='    if (au.features) for (k in au.features) { if (au.features[k]) cleared.features++; delIn(au.features, k); }';assert o in s;s=s.replace(o,'    if (au.features) for (k in au.features) { if (au.features[k]) cleared.features++; setIn(au.features, k, false); }');open(p,'w').write(s)" \
  $UNIT

echo
echo "the V4 mutant round is done — every mutant above must have reddened at least one row of its own leg."
