#!/usr/bin/env bash
# The U14 mutant round (docs/mobile.md, "The split"). Each mutation breaks exactly ONE claim and must redden the
# check that exists for it — by NAME, out of gate M1's own JSON row — while leaving the others alone.
#
# ⛔ RESTORED FROM A COPY, NEVER FROM GIT (the U9 round's rule: a harness that restores with `git checkout`
# restores over uncommitted work). The copies are taken first and the script refuses to start on a dirty tree.
# ⚠ `-uno`: in a WORKTREE `node_modules` is a SYMLINK and `.gitignore`'s `node_modules/` does not match one.
#
# ⛔ DO NOT EDIT THIS FILE WHILE IT IS RUNNING: bash reads a script by byte offset.
#
#   bash tools/harness/mutants-u14.sh <out-dir> [name-filter]
#
# ⚠ THE GAMES:
#   · `ptr`              — the witness: at a fresh save `p` is reachable, so the engine splits (a 634 px `col left`
#                          and the tab at x 646 at 1280x800).
#   · `the-modding-tree` — the CONTROL only: one of the five whose tree tab is `tree`, so the "is the tab the
#                          tree?" half of the derivation is U10's answer and not the literal `'none'`.
set -uo pipefail
cd "$(dirname "$0")/../.."
OUT="${1:?usage: mutants-u14.sh <out-dir> [name-filter]}"
ONLY="${2:-}"
mkdir -p "$OUT"
if [ -n "$(git status --porcelain -uno)" ]; then echo "REFUSING: tracked files are modified. Commit first — a mutant round restores over whatever is here."; exit 1; fi
FILES="loader/navbar.js loader/layerlist.js loader/layerlist.css"
for f in $FILES; do cp "$f" "$OUT/$(basename "$f").orig"; done
restore() { for f in $FILES; do cp "$OUT/$(basename "$f").orig" "$f"; done; }
trap restore EXIT

# The named checks, read out of gate M1's own JSON row.
#   desk   — leg S, the desktop half: Layers puts the list in `#treeTab`'s box with the tab still open and the right
#            column uncovered; Tree gives the column back with the tab STILL open; a 390 px desktop window keeps
#            the split; with no tab open the list is the full-window overlay it always was.
#   phone  — leg S, the phone half: `?mobile=1` with a tab open is exempt BY NAME (`split()` says `mobile`), the
#            list is the full window, nothing is stored, and Tree goes to the tree.
#   tree   — leg 3a (U10), a PRE-EXISTING phone leg: the real Tree press puts the engine on its tree, and from an
#            open tab brings it back.
#   lphone — leg 6's phone half (the layer list at 390 px), another pre-existing phone leg.
# ⚠ A leg that ABSTAINS reads as GREEN here, and the row prints the verdicts so an abstention is visible.
LEGS="desk phone tree lphone"

read_row() {
  node tools/harness/page.mjs "$1" --gate mobile 2>/dev/null | node -e '
    let s = ""; process.stdin.on("data", (d) => { s += d; });
    process.stdin.on("end", () => {
      const line = s.split("\n").filter((l) => l.startsWith("{")).pop();
      if (!line) { console.log("PARSE=false"); return; }
      const d = JSON.parse(line);
      const S = d.split || {};
      const RED = /^(THE |PRESSING |A NARROW |WITH NO TAB|TREE |LAYERS )/;
      const o = { desk: !!S.desktopVerdict && !RED.test(S.desktopVerdict), phone: !!S.phoneVerdict && !RED.test(S.phoneVerdict),
        tree: d.treeButtonOk, lphone: !!(d.layers && d.layers.phoneOk) };
      console.log(Object.entries(o).map(([k, v]) => `${k}=${v === true}`).join(" ")
        + ` || desk: ${S.desktopVerdict} || phone: ${S.phoneVerdict} || tree: ${d.treeButton && d.treeButton.verdict}`);
    });'
}

# $1 = name, $2 = python mutation, $3.. = one `<game>=<leg>,<leg>` per game (an empty list is spelled `<game>=`).
mutant() {
  local name="$1" mut="$2"; shift 2
  local spec=("$@")
  if [ -n "$ONLY" ] && [[ "$name" != *"$ONLY"* ]]; then return 0; fi
  restore
  python3 -c "$mut" || { echo "$name: THE MUTATION DID NOT APPLY"; return 1; }
  echo "=== $name  (expects: ${spec[*]:-nothing red})"
  git --no-pager diff --stat -- $FILES | tail -1
  local ok=1
  for e in "${spec[@]}"; do
    local g="${e%%=*}" want="${e#*=}"
    want="${want//,/ }"
    local out; out="$(read_row "$g")"
    echo "  $g: $out" | tee -a "$OUT/$name.log"
    local red=()
    for leg in $LEGS; do grep -q -- "$leg=true" <<<"$out" || red+=("$leg"); done
    local got="${red[*]:-}"
    if [ "$got" = "$want" ]; then echo "  OK   $g — red: [${got:-none}]"
    else echo "  FAIL $g — red: [${got:-none}], expected [${want:-none}]"; ok=0; fi
  done
  [ "$ok" = 1 ] && echo "  => $name OK" || echo "  => $name FAILED"
  restore
  git --no-pager diff --stat -- $FILES | grep . && echo "!! NOT RESTORED" || echo "  restored: diff is empty"
}

echo "control (no mutant):"
mutant control "pass" ptr= the-modding-tree=

# (1) THE DESKTOP BRANCH ON THE PHONE TOO: the `mobile` guard deleted. ⚠ On its own this is nearly inert — the
#     phone layout HIDES `.col.left` (mobile.css §2), so the derivation falls through to `no box` and the overlay
#     stays full-window. What reddens is the phone half's demand that the exemption is BY NAME.
mutant m1-phone-not-exempt \
  "p='loader/layerlist.js';s=open(p).read();o=\"    if (T.mobile) return { split: false, why: 'mobile' };\n\";assert o in s;s=s.replace(o,'');open(p,'w').write(s)" \
  ptr=phone

# (1b) …and the stronger form, where nothing else stands in the way either (the guard AND the box test gone): the
#      phone then takes the desktop branch in full — a zero-width list, and Tree no longer leaving the tab. A
#      PRE-EXISTING phone leg, U10's Tree press, reddens beside leg S's own phone half.
mutant m1b-phone-takes-the-desktop-branch \
  "p='loader/layerlist.js';s=open(p).read();o=\"    if (T.mobile) return { split: false, why: 'mobile' };\n\";assert o in s;s=s.replace(o,'');o2=\"    if (!(r.width > 0 && r.height > 0)) return { split: false, why: 'no box', tab: tab };\n\";assert o2 in s;s=s.replace(o2,'');open(p,'w').write(s)" \
  ptr=phone,tree

# (2) THE ENGINE'S SPLIT REPLACED BY A VIEWPORT WIDTH — the tempting build. Green at 1280 px; red at a 390 px
#     DESKTOP window, which is still the desktop layout (the engine still splits there, 193 px a column).
mutant m2-width-test \
  "p='loader/layerlist.js';s=open(p).read();o=\"    if (!(col.classList.contains('col') && col.classList.contains('left'))) return\";assert o in s;s=s.replace(o,\"    if (window.innerWidth < 768) return { split: false, why: 'narrow', tab: tab };\n    if (false) return\");open(p,'w').write(s)" \
  ptr=desk

# (3) TREE CLOSES THE TAB IN THE SPLIT — the pre-U14 press, after putting the tree back in the column.
mutant m3-tree-closes-the-tab \
  "p='loader/navbar.js';s=open(p).read();o='        if (inSplit && e.target === null) return T.layerListUI.showTree();';assert o in s;s=s.replace(o,'        if (inSplit && e.target === null) { T.layerListUI.showTree(); return onTree(); }');open(p,'w').write(s)" \
  ptr=desk

# (4) THE COLUMN'S BOX NOT APPLIED: the list says "split" and still covers the window — the case a probe that
#     trusted `split()` would pass.
mutant m4-overlay-still-full-window \
  "p='loader/layerlist.js';s=open(p).read();o=\"      panel.style.width = s.split ? s.width + 'px' : '';\n\";assert o in s;s=s.replace(o,'');p2='loader/layerlist.css';c=open(p2).read();o2='#tmt-layerlist.tmt-layerlist-split { right: auto; }';assert o2 in c;c=c.replace(o2,'');open(p2,'w').write(c);open(p,'w').write(s)" \
  ptr=desk
