#!/usr/bin/env bash
# The R3a mutant round — the challenge GIVE-UP rule, its RETRY bar, and what a PAUSE on the kind leaves behind.
#
# ⛔ FOR EVERY MUTANT, THE TWO QUESTIONS (V4's Part 5, kept):
#   1. CAN IT MOVE ITS ROW'S OWN REFERENCE? Every row in `loader/challenges.test.mjs` is driven by a CURVE that the
#      test supplies and the loader cannot touch, and by the stub's own completion rule. A mutation inside the
#      give-up path cannot move the curve it is judged against, so the reference is out of reach by construction.
#      The one row whose reference IS the loader's own behaviour is `sequential` without the modifier — and every
#      mutation below is inside a branch only a feature WITH the modifier reaches, so that row is the control.
#   2. DOES A SECOND GUARD MAKE IT REDUNDANT? Named beside the ones where it does. A mutant that only changes a
#      LABEL is excluded on purpose (V4's rule): the four new codes are asserted both in the vocabulary table
#      (`gates-v1 --part 1`) and as values on real decisions here, so dropping one reddens two rows and proves
#      nothing about the mechanism.
#
# ⛔ RESTORED FROM A COPY, NEVER FROM GIT — a harness that restores with `git checkout` restores over uncommitted
# work. The script refuses to start on a dirty tree, because a dirty tree is the case where the copy is the only
# thing between the mutation and the work.
#
# ⛔ DO NOT EDIT THIS FILE WHILE IT IS RUNNING. Bash reads a script incrementally, by byte offset.
#
#   bash tools/harness/mutants-r3.sh <out-dir> [name-filter]
set -uo pipefail
cd "$(dirname "$0")/../.."
OUT="${1:?usage: mutants-r3.sh <out-dir> [name-filter]}"
ONLY="${2:-}"
mkdir -p "$OUT"
if [ -n "$(git status --porcelain)" ]; then echo "REFUSING: the tree is dirty. Commit first — a mutant round restores over whatever is here."; exit 1; fi
AUTO=loader/tmt-auto.js
cp "$AUTO" "$OUT/tmt-auto.js.orig"
restore() { cp "$OUT/tmt-auto.js.orig" "$AUTO"; }
trap restore EXIT

mutant() {
  local name="$1" mut="$2"; shift 2
  if [ -n "$ONLY" ] && [[ "$name" != *"$ONLY"* ]]; then return 0; fi
  restore
  python3 -c "$mut" || { echo "$name: THE MUTATION DID NOT APPLY"; return 1; }
  echo "=== $name ==="
  git --no-pager diff --stat -- "$AUTO"
  "$@" > "$OUT/$name.log" 2>&1
  echo "$name: exit $? — $(grep -cE '^(RED|not ok)' "$OUT/$name.log") RED row(s), $(grep -cE '^(GREEN|ok )' "$OUT/$name.log") green"
  grep -E '^(RED|not ok)' "$OUT/$name.log" | cut -c1-260
  restore
  git --no-pager diff --stat -- "$AUTO" | grep . && echo "!! NOT RESTORED" || echo "restored: diff is empty"
}

UNIT="node --test loader/challenges.test.mjs"

# ---- the EXIT rule -------------------------------------------------------------------------------------------------
# NEVER GIVES UP — the state the whole slice exists to leave. It is the pre-slice behaviour, so this mutant also
# says what the modifier is worth: without it, `sequential` is exactly what it was.
mutant m1-never-gives-up \
  "p='$AUTO';s=open(p).read();o='    if (held >= h) return { give: true,';assert o in s;s=s.replace(o,'    if (false) return { give: true,');open(p,'w').write(s)" \
  $UNIT

# ⛔ THE ONE THE MEASUREMENT FOUND. The window's anchor never moves, so every window is measured from ENTRY — which
# is the front-loaded defect: PTR's H11 closes 43 % of the gap in its first ten seconds and nothing later comes near
# it, so an entry-anchored rule abandons a challenge it is five seconds from winning. No other guard sees this: the
# plateau row is GREEN under it.
mutant m2-window-anchored-at-entry \
  "p='$AUTO';s=open(p).read();o='{ m.anchorAt = now; m.anchorP = p; m.held = null;';assert o in s;s=s.replace(o,'{ m.anchorAt = now; m.held = null;');open(p,'w').write(s)" \
  $UNIT

# GIVES UP WHILE STILL CLIMBING — B read as a fraction of the WHOLE goal rather than of what is LEFT. Near the goal
# the remaining distance is small and a fixed fraction of the whole is unreachable, so a winning attempt is conceded.
mutant m3-bar-is-a-fraction-of-the-whole \
  "p='$AUTO';s=open(p).read();o='    var need = gap > 0 ? b * gap : 0;';assert o in s;s=s.replace(o,'    var need = b;');open(p,'w').write(s)" \
  $UNIT

# THE STRICTNESS. `>=` makes a dead-flat attempt read as progress at B = 0 (it closes exactly 0 of 0), so the BARE
# rule — the control every other setting is measured against — stops working while every buffered setting still does.
mutant m4-a-flat-window-counts-as-progress \
  "p='$AUTO';s=open(p).read();o='    if (closed > need) {';assert o in s;s=s.replace(o,'    if (closed >= need) {');open(p,'w').write(s)" \
  $UNIT

# THE ENGINE'S LAST WORD. A fork that refuses to let go of a challenge (`canExitChallenge`) must still be obeyed;
# dropping the guard makes the loader walk out of a challenge the game says it cannot leave.
mutant m5-the-engine-s-exit-refusal-ignored \
  "p='$AUTO';s=open(p).read();o=\"        if (typeof canExitChallenge === 'function' && !canExitChallenge(l, pick)) return { act: false, code: 'blocked:exit', values: { id: pick } };\n        // ⛔ THE STRENGTH THIS ATTEMPT STARTED FROM\";assert o in s;s=s.replace(o,\"        // ⛔ THE STRENGTH THIS ATTEMPT STARTED FROM\");open(p,'w').write(s)" \
  $UNIT

# ---- the RETRY bar -------------------------------------------------------------------------------------------------
# NO RETRY AT ALL — the oscillator. `sequential` re-picks the challenge it has just left on the next tick, so this is
# not a small regression: it is an enter/fail/leave loop at two forced layer resets a cycle.
mutant m6-no-retry \
  "p='$AUTO';s=open(p).read();o='    if (!rec || rec[id] === undefined) return null;';assert o in s;s=s.replace(o,'    return null;');open(p,'w').write(s)" \
  $UNIT

# R2's EMPTY-PURSE FLOOR, REMOVED. `R × 0` is `0`, i.e. no condition at all — the same defect R2 found in `gain>=Nx`,
# and it bites on exactly the layer a challenge belongs to before its first reset.
mutant m7-retry-without-the-unit-floor \
  "p='$AUTO';s=open(p).read();o='  function layerHeld(l) { var h = D(player[l] && player[l].points); return h.lt(D(1)) ? D(1) : h; }';assert o in s;s=s.replace(o,'  function layerHeld(l) { return D(player[l] && player[l].points); }');open(p,'w').write(s)" \
  $UNIT

# ---- the pause, and the plumbing --------------------------------------------------------------------------------
# A STRANDED PAUSE READS AS AN ORDINARY GATE — the measured defect this code exists for. ⚠ It is NOT redundant with
# the vocabulary row: `blocked:gate` is a perfectly good code and the run still pauses, so nothing but a row that
# asks WHICH code and WHICH control can see it.
mutant m9-a-stranded-pause-reads-as-an-ordinary-gate \
  "p='$AUTO';s=open(p).read();o='    if (!STRANDED[f.kind]) return null;';assert o in s;s=s.replace(o,'    return null;');open(p,'w').write(s)" \
  $UNIT

# THE KIND READS THE POLICY STRING — the defect the modifier introduces if nobody looks: with a modifier the string
# is `sequential|give-up@…`, so a bare string comparison turns the WHOLE feature off and reports `off:policy`.
mutant m10-the-kind-reads-the-policy-string \
  "p='$AUTO';s=open(p).read();o=\"      if (!P || P.id !== 'sequential') return { act: false, code: 'off:policy'\";assert o in s;s=s.replace(o,\"      if (f.policy !== 'sequential') return { act: false, code: 'off:policy'\");open(p,'w').write(s)" \
  $UNIT

# THE SEEDED WINDOW. A resumed run that finds itself inside a challenge with no record would be judged as an attempt
# that began at time zero, and would be given up on its first tick.
mutant m11-the-attempt-is-not-seeded \
  "p='$AUTO';s=open(p).read();o='held: null, anchorAt: now, anchorP: null';assert o in s;s=s.replace(o,'held: null, anchorAt: 0, anchorP: null');open(p,'w').write(s)" \
  $UNIT

# THE RETRY BAR IS MEASURED AT ENTRY, and this is the mutant that says why the FIELD exists. ⚠ It is void on PTR by
# accident and not by design: `rowReset` leaves a SAME-ROW layer's own data alone unless that layer's own `doReset`
# wipes it (games/ptr/js/game.js), and PTR's `h` does not — so the entry reading and the give-up reading coincide
# there. A fork whose `doReset` wipes its own layer is the case the row is written for, and the stub supplies it.
mutant m13-retry-bar-read-at-the-give-up \
  "p='$AUTO';s=open(p).read();o='(chFailed[f.id] || (chFailed[f.id] = {}))[pick] = chAttempt[f.id].startHeld;';assert o in s;s=s.replace(o,'(chFailed[f.id] || (chFailed[f.id] = {}))[pick] = String(layerHeld(l));');open(p,'w').write(s)" \
  $UNIT

# THE MEMORY IS NOT IN THE RECORD — a resumed run would re-enter a challenge it had already given up on, and a
# snapshot taken mid-attempt would restart its window.
mutant m12-the-memory-is-not-in-the-record \
  "p='$AUTO';s=open(p).read();o='    if (ncg) o.challengeFailed = cg;';assert o in s;s=s.replace(o,'');open(p,'w').write(s)" \
  $UNIT
