#!/usr/bin/env bash
# The U9 mutant round (docs/mobile.md, "The tree canvas follows the page" and "The global currency on a first-row
# card"). Each mutation breaks exactly ONE claim and must redden the check that exists for it — by NAME, out of
# gate M1's own JSON row — while leaving the others alone.
#
# ⛔ RESTORED FROM A COPY, NEVER FROM GIT. A harness that restores with `git checkout` restores over uncommitted
# work; this repo has lost mutants that way before. The copies are taken first, the tree is restored from them
# after every run, and the script refuses to start on a dirty tree.
# ⚠ `-uno`: in a WORKTREE `node_modules` is a SYMLINK, and `.gitignore`'s `node_modules/` does not match one, so
# the plain check refuses on every worktree. Tracked files are what a mutant round can damage.
#
# ⛔ DO NOT EDIT THIS FILE WHILE IT IS RUNNING: bash reads a script by byte offset and an edit mid-run resumes it
# in the middle of a word.
#
#   bash tools/harness/mutants-u9.sh <out-dir> [name-filter]
#
# ⚠ THE GAMES ARE PER MUTANT, taken from its own expectation list, because most of them are invisible on most
# games and a roster-wide expectation would have to be the weaker of the two:
#   · `ptr`            — the only game with a deep snapshot AND a scrolling tree AND a row-0 layer (`p`) that
#                        declares the global currency. It is the sole witness for every tree-canvas mutant.
#   · `the-snake-tree` — three row-0 declarers, two of them labelled `TBD`, so it is the witness for the LABEL.
#   · `the-cultree`    — one declarer, `c:Faith`, and a second scrolling tree.
#   · `gooby-cat-tree` — `p` and `Fr` carry a commented-out `//return player.points` and NOTHING ELSE declares the
#                        global currency, which makes it two things at once: the only witness for the comment strip
#                        (m5) and the CONTROL for every other resource mutant — it must stay green throughout, and
#                        that is what says a red elsewhere is the mutation and not the run.
#                        ⚠ `the-cultree` was the control in the first round and it was WRONG: its `c` declares the
#                        global currency (label `Faith`), so m3/m6/m8 reddened it and the round called them failed.
#   · `the-lime-upgrade-tree`, `the-chronicle-tree` — the only shape that can witness m4. Measured over the whole
#                        roster: the SOURCE rule and a VALUE-EQUALITY rule disagree on 10 of the 171 games, and on
#                        neither `ptr` nor `the-snake-tree` — where the first round found m4 green on every game.
set -uo pipefail
cd "$(dirname "$0")/../.."
OUT="${1:?usage: mutants-u9.sh <out-dir> [name-filter]}"
ONLY="${2:-}"
mkdir -p "$OUT"
if [ -n "$(git status --porcelain -uno)" ]; then echo "REFUSING: tracked files are modified. Commit first — a mutant round restores over whatever is here."; exit 1; fi
FILES="loader/mobile.css loader/navbar.js loader/layerlist.js"
for f in $FILES; do cp "$f" "$OUT/$(basename "$f").orig"; done
restore() { for f in $FILES; do cp "$OUT/$(basename "$f").orig" "$f"; done; }
trap restore EXIT

# The named checks, read out of gate M1's own JSON row.
#   treeTop     — leg 3b: the branches are on their nodes at the TOP of the page. ⚠ This one is GREEN on the
#                 unfixed build too — the two coordinate spaces agree at scroll 0 — so a mutant that reddens it
#                 has been caught by the wrong assertion.
#   treeBottom  — leg 3b, scrolled, with a redraw FORCED: `position: fixed` on its own
#   treeRedraw  — leg 3b: `navbarUI.treeRedraws()` moved on the scroll — the loader's listener on its own
#   treeLive    — leg 3b, scrolled and NOT redrawn by us: the two together
#   res         — leg 6's other-resources rebuild, which is where the DECLARED global row is judged, both ways
# ⚠ A leg that ABSTAINS reads as GREEN here, and the row prints the verdict so an abstention is visible rather
# than counted as a pass.
LEGS="treeTop treeBottom treeRedraw treeLive res"

read_row() {
  node tools/harness/page.mjs "$1" --gate mobile 2>/dev/null | node -e '
    let s = ""; process.stdin.on("data", (d) => { s += d; });
    process.stdin.on("end", () => {
      const line = s.split("\n").filter((l) => l.startsWith("{")).pop();
      if (!line) { console.log("PARSE=false"); return; }
      const d = JSON.parse(line);
      const L = (d.layers && d.layers.phone) || {};
      const T = d.tree || {};
      const abst = /abstains/.test(String(T.verdict || "")) || !T.verdict;
      const o = { treeTop: abst || T.topOk, treeBottom: abst || (T.bottomOk && T.spaceOk),
        treeRedraw: abst || T.redrawOk, treeLive: abst || T.liveOk, res: L.resOk && L.resMemKeyOk };
      console.log(Object.entries(o).map(([k, v]) => `${k}=${v === true}`).join(" ")
        + ` || tree: ${T.verdict} || global: ${JSON.stringify(L.resGlobalCards)} rows=${L.resGlobalRows}`
        + ` || ${JSON.stringify((L.resBad || []).slice(0, 2))}`);
    });'
}

# $1 = name, $2 = python mutation, $3.. = one `<game>=<leg>,<leg>` per game (an empty list is spelled `<game>=`).
# The GAMES RUN are exactly the ones named here.
mutant() {
  local name="$1" mut="$2"; shift 2
  local spec=("$@")
  if [ -n "$ONLY" ] && [[ "$name" != *"$ONLY"* ]]; then return 0; fi
  restore
  python3 -c "$mut" || { echo "$name: THE MUTATION DID NOT APPLY"; return 1; }
  echo "=== $name  (expects: ${spec[*]:-nothing red})"
  git --no-pager diff --stat -- $FILES | tail -1
  local ok=1
  for e in "${spec[@]}"; do
    local g="${e%%=*}" want="${e#*=}"
    want="${want//,/ }"
    local out; out="$(read_row "$g")"
    echo "  $g: $out" | tee -a "$OUT/$name.log"
    local red=()
    for leg in $LEGS; do grep -q -- "$leg=true" <<<"$out" || red+=("$leg"); done
    local got="${red[*]:-}"
    if [ "$got" = "$want" ]; then echo "  OK   $g — red: [${got:-none}]"
    else echo "  FAIL $g — red: [${got:-none}], expected [${want:-none}]"; ok=0; fi
  done
  [ "$ok" = 1 ] && echo "  => $name OK" || echo "  => $name FAILED"
  restore
  git --no-pager diff --stat -- $FILES | grep . && echo "!! NOT RESTORED" || echo "  restored: diff is empty"
}

echo "control (no mutant):"
mutant control "pass" ptr= the-snake-tree= the-cultree= gooby-cat-tree=

# ---- item 1: the tree canvas ------------------------------------------------------------------------------------
# (1) the canvas back in DOCUMENT space — the build before this slice. ⛔ It must redden the SCROLLED readings and
#     LEAVE THE AT-TOP ONE GREEN: the branch offset IS zero at the top of the page, and a mutant that reddened
#     both would say nothing about the defect the user reported.
mutant m1-canvas-back-in-document-space \
  "p='loader/mobile.css';s=open(p).read();o='html.tmt-mobile canvas.canvas { position: fixed; }';assert o in s;s=s.replace(o,'html.tmt-mobile canvas.canvas { position: absolute; }');open(p,'w').write(s)" \
  ptr=treeBottom,treeLive

# (2) the loader's scroll listener removed — the canvas is in the right space but nobody redraws it after a scroll.
#     ⚠ `treeBottom` must stay GREEN: that reading forces a redraw, so it cannot see a missing listener. `treeLive`
#     is the one that can, and it is why the leg reads the same place twice.
mutant m2-scroll-listener-removed \
  "p='loader/navbar.js';s=open(p).read();o=\"    if (T.mobile) window.addEventListener('scroll', onScroll, { passive: true });\";assert o in s;s=s.replace(o,'');open(p,'w').write(s)" \
  ptr=treeRedraw,treeLive

# ---- item 2: the global currency --------------------------------------------------------------------------------
# (3) the row never emitted — the build before this slice. `gooby-cat-tree` has no declaring card and must stay green.
mutant m3-global-row-not-emitted \
  "p='loader/layerlist.js';s=open(p).read();o='    if (rowOf(l) !== 0) return null;';assert o in s;s=s.replace(o,'    if (rowOf(l) !== 0) return null;\n    return null;');open(p,'w').write(s)" \
  ptr=res the-snake-tree=res the-cultree=res gooby-cat-tree=

# (4) the rule asked as a VALUE comparison instead of a SOURCE read — the mistake this item's first measurement
#     made. ⚠ ITS WITNESS HAD TO BE MEASURED, and the first round found it GREEN on ptr, the-snake-tree and
#     the-cultree: on those games, at the states the sweep drives, the two rules HAPPEN TO AGREE, which is exactly
#     what makes the wrong rule look right. A roster sweep of both predicates found them disagreeing on 10 of the
#     171 games; `the-lime-upgrade-tree` declares NONE and value-equality claims 2 (`L`, `lemons`), and
#     `the-chronicle-tree` declares 5 and value-equality claims 6.
#     ⚠ AND ONLY THE FIRST OF THOSE TWO ACTUALLY WITNESSES IT: a layer the list does not SHOW a card for cannot
#     redden anything, and the-chronicle-tree's extra layer `e` has no card at the state the sweep drives. It
#     stays in the round as the measured near-miss rather than being quietly dropped.
mutant m4-value-equality-instead-of-source \
  "p='loader/layerlist.js';s=open(p).read();o=\"    if (!BASE_IS_GLOBAL.test(src)) return null;\";assert o in s;s=s.replace(o,\"    if (!safe(function () { var b = tmp[l].baseAmount; return !!b && !!player.points && String(b) === String(player.points); }, false)) return null;\");open(p,'w').write(s)" \
  the-lime-upgrade-tree=res the-chronicle-tree= gooby-cat-tree=

# (5) comments NOT stripped. ⚠ Only `gooby-cat-tree` can witness it — its `p` and `Fr` are the only two layers on
#     the roster whose `baseAmount` mentions the global currency in a comment and not in code.
mutant m5-comments-not-stripped \
  "p='loader/layerlist.js';s=open(p).read();o=\"  function stripComments(src) { return String(src).replace(/\\\\/\\\\*[\\\\s\\\\S]*?\\\\*\\\\//g, ' ').replace(/\\\\/\\\\/[^\\\\n\\\\r]*/g, ' '); }\";assert o in s;s=s.replace(o,'  function stripComments(src) { return String(src); }');open(p,'w').write(s)" \
  gooby-cat-tree=res ptr= the-cultree=

# (6) the label taken from the KEY instead of the author's `baseResource`. `the-snake-tree` is the sharpest witness
#     (two of its three declarers are labelled `TBD`), but any declaring card reddens.
mutant m6-label-is-the-key \
  "p='loader/layerlist.js';s=open(p).read();o=\"    return { key: GLOBAL_RES_KEY, label: label || 'points', value: v };\";assert o in s;s=s.replace(o,\"    return { key: GLOBAL_RES_KEY, label: GLOBAL_RES_KEY, value: v };\");open(p,'w').write(s)" \
  ptr=res the-snake-tree=res the-cultree=res gooby-cat-tree=

# (7) the ROW-0 restriction dropped: every declaring layer gets the row, not just the first one.
mutant m7-row-0-restriction-dropped \
  "p='loader/layerlist.js';s=open(p).read();o='    if (rowOf(l) !== 0) return null;';assert o in s;s=s.replace(o,'');open(p,'w').write(s)" \
  ptr=res the-snake-tree=res the-cultree=res gooby-cat-tree=

# (8) the DECLARED row written into the remembered set. ⚠ It renders identically — only the store moves — so the
#     only check that can see it is the one that asks the store by name.
mutant m8-declared-row-remembered \
  "p='loader/layerlist.js';s=open(p).read();o='      var gCollide = gShown !== null && byText[gShown] > 1;';assert o in s;s=s.replace(o,'      var gCollide = gShown !== null && byText[gShown] > 1;\n      seenAdd(l, g.key);');open(p,'w').write(s)" \
  ptr=res the-snake-tree=res the-cultree=res gooby-cat-tree=

# (9) the declared row claims AFTER the candidates instead of before.
#     ⛔ VOID AT EVERY STATE THIS ROUND CAN REACH, and that was MEASURED rather than assumed — it is kept here,
#     labelled, so the next slice does not spend the same hour rediscovering it. The mutation can only show where a
#     NON-ENGINE `player[l]` key holds exactly the global's formatted value AND the layer's text still has an
#     unclaimed occurrence of it after `points`/`best`/`total`/`spentOnBuyables` have taken theirs. A roster sweep
#     of the first two conditions found 13 games, but in nearly all of them the matching keys ARE the engine's own
#     four (which claim first either way); the two with non-engine candidates — `the-dressy-tree` (`G.gen*`) and
#     `the-chronicle-tree` (`g.air_cur_progress`, `g.tot_time`, …) — both come back GREEN, because the engine
#     readouts consume every occurrence of `0.00` before either claimant reaches it.
#     ⚠ So the claim-order rule is DOCUMENTED and unasserted. A witness needs a deep save on a game with a
#     non-engine candidate equal to the global, and there are two recorded snapshots on the roster.
mutant m9-declared-row-claims-last \
  "p='loader/layerlist.js';s=open(p).read();o='    if (g && text) { gShown = takeOccurrence(text, budget, g.value); if (gShown !== null) byText[gShown] = (byText[gShown] || 0) + 1; }';assert o in s;s=s.replace(o,'');open(p,'w').write(s)" \
  the-dressy-tree= the-chronicle-tree=
