#!/usr/bin/env bash
# The U10 mutant round (docs/mobile.md, "Pressing Tree really shows the tree" and "A buyable chip says how many
# you own"). Each mutation breaks exactly ONE claim and must redden the check that exists for it — by NAME, out
# of gate M1's own JSON row — while leaving the others alone.
#
# ⛔ RESTORED FROM A COPY, NEVER FROM GIT (the U9 round's rule, and the reason is the same: a harness that
# restores with `git checkout` restores over uncommitted work). The copies are taken first and the script refuses
# to start on a dirty tree.
# ⚠ `-uno`: in a WORKTREE `node_modules` is a SYMLINK and `.gitignore`'s `node_modules/` does not match one.
#
# ⛔ DO NOT EDIT THIS FILE WHILE IT IS RUNNING: bash reads a script by byte offset.
#
#   bash tools/harness/mutants-u10.sh <out-dir> [name-filter]
#
# ⚠ THE GAMES ARE PER MUTANT, taken from its own expectation list:
#   · `the-modding-tree` — one of the FIVE whose engine calls the tree tab `tree`. It is the witness for every
#                          item-1 mutant, and it draws NO buyable chip at a fresh save, so it is also the
#                          CONTROL for every item-2 one.
#   · `ptr`              — the control for item 1 (its tree tab really is `none`, so a bar that hardcodes the
#                          name is right about it), and the sole witness for item 2: 21 of the roster's 56
#                          buyable chips are its, and it is one of the three games whose `getBuyableAmount` is
#                          NOT `player[l].buyables[id]` — which is what the constructed `reader` witness needs.
set -uo pipefail
cd "$(dirname "$0")/../.."
OUT="${1:?usage: mutants-u10.sh <out-dir> [name-filter]}"
ONLY="${2:-}"
mkdir -p "$OUT"
if [ -n "$(git status --porcelain -uno)" ]; then echo "REFUSING: tracked files are modified. Commit first — a mutant round restores over whatever is here."; exit 1; fi
FILES="loader/mobile.css loader/navbar.js loader/layerlist.js loader/layerlist.css"
for f in $FILES; do cp "$f" "$OUT/$(basename "$f").orig"; done
restore() { for f in $FILES; do cp "$OUT/$(basename "$f").orig" "$f"; done; }
trap restore EXIT

# The named checks, read out of gate M1's own JSON row.
#   tree    — leg 3a: the REAL Tree press puts the engine on its own tree, a node is visible, a layer tab still
#             takes the screen, Tree brings it back, and the bar marks Tree as the open view.
#             ⛔ GREEN AT LOAD ON EVERY GAME, including the five — which is why the leg presses the button.
#   counts  — leg 6's per-card `countOk`: every buyable chip AND action button prints `getBuyableAmount`, the two
#             views say the same thing, the title carries it, and nothing else carries a count.
#   reader  — the CONSTRUCTED witness: with the layer locked, `getBuyableAmount` and `player[l].buyables[id]`
#             disagree and the chip must follow the accessor. ⚠ ABSTAINS on 168 of the 171.
#   digits  — U2c's leg, which since U10 also writes the count's own box over every reserved digit column.
# ⚠ A leg that ABSTAINS reads as GREEN here, and the row prints the verdict so an abstention is visible.
LEGS="tree counts reader digits"

read_row() {
  node tools/harness/page.mjs "$1" --gate mobile 2>/dev/null | node -e '
    let s = ""; process.stdin.on("data", (d) => { s += d; });
    process.stdin.on("end", () => {
      const line = s.split("\n").filter((l) => l.startsWith("{")).pop();
      if (!line) { console.log("PARSE=false"); return; }
      const d = JSON.parse(line);
      const L = (d.layers && d.layers.phone) || {};
      const R = (d.rules && d.rules.countReader) || {};
      const o = { tree: d.treeButtonOk, counts: L.countOk, digits: d.digitsOk,
        reader: /abstains/.test(String(R.verdict || "")) || !/NOT THE ENGINE|NOT RESTORED/.test(String(R.verdict || "")) };
      console.log(Object.entries(o).map(([k, v]) => `${k}=${v === true}`).join(" ")
        + ` || tree: ${d.treeButton && d.treeButton.verdict} || reader: ${R.verdict}`
        + ` || counts: ${L.countChips} chip(s) ${JSON.stringify((L.countBad || []).slice(0, 2))}`
        + ` || digits: ${d.digits && d.digits.verdict}`);
    });'
}

# $1 = name, $2 = python mutation, $3.. = one `<game>=<leg>,<leg>` per game (an empty list is spelled `<game>=`).
mutant() {
  local name="$1" mut="$2"; shift 2
  local spec=("$@")
  if [ -n "$ONLY" ] && [[ "$name" != *"$ONLY"* ]]; then return 0; fi
  restore
  python3 -c "$mut" || { echo "$name: THE MUTATION DID NOT APPLY"; return 1; }
  echo "=== $name  (expects: ${spec[*]:-nothing red})"
  git --no-pager diff --stat -- $FILES | tail -1
  local ok=1
  for e in "${spec[@]}"; do
    local g="${e%%=*}" want="${e#*=}"
    want="${want//,/ }"
    local out; out="$(read_row "$g")"
    echo "  $g: $out" | tee -a "$OUT/$name.log"
    local red=()
    for leg in $LEGS; do grep -q -- "$leg=true" <<<"$out" || red+=("$leg"); done
    local got="${red[*]:-}"
    if [ "$got" = "$want" ]; then echo "  OK   $g — red: [${got:-none}]"
    else echo "  FAIL $g — red: [${got:-none}], expected [${want:-none}]"; ok=0; fi
  done
  [ "$ok" = 1 ] && echo "  => $name OK" || echo "  => $name FAILED"
  restore
  git --no-pager diff --stat -- $FILES | grep . && echo "!! NOT RESTORED" || echo "  restored: diff is empty"
}

echo "control (no mutant):"
mutant control "pass" the-modding-tree= ptr=

# ---- item 1: the Tree button ------------------------------------------------------------------------------------
# (1) THE BUILD BEFORE THIS SLICE: the tree tab hardcoded to `'none'`. ⛔ It must redden `the-modding-tree` and
#     LEAVE `ptr` GREEN — `ptr`'s tree really is `none`, so a hardcoded name is right about it, and a mutant that
#     reddened both would say nothing about the five games this is for.
mutant m1-tree-tab-hardcoded-none \
  "p='loader/navbar.js';s=open(p).read();o='    try { showTab(treeTab()); } catch (e)';assert o in s;s=s.replace(o,'    try { showTab(\'none\'); } catch (e)');open(p,'w').write(s)" \
  the-modding-tree=tree ptr=

# (2) the BAR's own active state back on the literal. The page is right and only the highlight is wrong, so this
#     is the half that `shows`/`nodes` cannot see.
mutant m2-active-state-hardcoded-none \
  "p='loader/navbar.js';s=open(p).read();o='player.tab === treeTab()';assert o in s;s=s.replace(o,\"player.tab === 'none'\");open(p,'w').write(s)" \
  the-modding-tree=tree ptr=

# (3) the derivation always answers `'none'` — the same defect one layer down, and the check that catches it is
#     the same one, which is what says the leg is about the ENGINE's answer and not about our regex.
mutant m3-derivation-returns-none \
  "p='loader/navbar.js';s=open(p).read();o='      if (m) treeName = m[1];';assert o in s;s=s.replace(o,'');open(p,'w').write(s)" \
  the-modding-tree=tree ptr=

# ---- item 2: the buyable counts ---------------------------------------------------------------------------------
# (4) THE READER SWAPPED for the direct `player[l].buyables[id]`. ⛔ VACUOUS ON THE ROSTER PASS — the two agree at
#     every state the sweep drives (0 of 56 chips disagree) — so the check that reddens is the CONSTRUCTED one.
mutant m4-count-from-player-not-accessor \
  "p='loader/layerlist.js';s=open(p).read();o='    var a = ownedAmount(\'buyables\', c.layer, c.id);';assert o in s;s=s.replace(o,'    var a = safe(function () { return player[c.layer].buyables[c.id]; }, null);');open(p,'w').write(s)" \
  ptr=reader the-modding-tree=

# (5) the count in the EXPANDED chip only — the collapsed action row left on its bare name. Half the user's ask.
mutant m5-count-in-one-view-only \
  "p='loader/layerlist.js';s=open(p).read();o='      drawChipText(b, c);   // (U10) THE SAME call the expanded chip makes';assert o in s;s=s.replace(o,'      b.textContent = c.chip; b.title = c.title;   // (U10) THE SAME call the expanded chip makes');open(p,'w').write(s)" \
  ptr=counts the-modding-tree=

# (6) THE RESERVATION REMOVED: the count is right and the chip resizes with it. ⚖ U2c is what this breaks, and
#     `digits` is the only leg that can see it.
mutant m6-count-width-not-reserved \
  "p='loader/layerlist.js';s=open(p).read();o='    for (var i = 0; i < qs.length; i++) qs[i].style.minWidth = want + \'ch\';';assert o in s;s=s.replace(o,'');open(p,'w').write(s)" \
  ptr=digits the-modding-tree=

# (7) the `title` left on the bare name. The chip says ×36 and the tooltip's first line does not — the one
#     disagreement U2e's rule exists to make impossible.
mutant m7-title-without-the-count \
  "p='loader/layerlist.js';s=open(p).read();o=\"    el.title = s === '' ? c.title : c.title + ' ' + COUNT_SIGN + s;\";assert o in s;s=s.replace(o,'    el.title = c.title;');open(p,'w').write(s)" \
  ptr=counts the-modding-tree=

# (8) THE ZERO HIDDEN — the plausible \"tidier\" build. ⚠ A buyable at zero still HAS a chip (the engines define
#     `getBuyableAmount` for it), so a chip that silently drops its count there is saying something different
#     about it than about its neighbours.
#     ⚠ IT REDDENS TWO LEGS, and that is not sloppiness in the mutant: `reader`'s construction ends with the
#     accessor at exactly 0, which is the value this mutation hides, so the witness necessarily sees it too. The
#     expectation names both rather than the round being called a failure for a mutation that discriminates.
mutant m8-zero-count-hidden \
  "p='loader/layerlist.js';s=open(p).read();o='    var s = t === null ? \'\' : t;';assert o in s;s=s.replace(o,'    var s = (t === null || t === \'0\') ? \'\' : t;');open(p,'w').write(s)" \
  ptr=counts,reader the-modding-tree=
