#!/usr/bin/env bash
# R3c's mutant round — the dead-member rule's HIGH-WATER reading (`turnMark`, plan §45).
#
# ⛔ FOR EVERY MUTANT, THE TWO QUESTIONS (V4's Part 5, kept): can it move its leg's OWN reference (the leg must build
# the thing it checks, not read it off the mutated build's history), and does a SECOND guard make it redundant?
# Every leg named here runs one scenario under two readings and asserts they DIFFER the promised way, so each leg is
# its own control — a mutant that makes two readings the same reds it by construction.
#
# ⚠ `m-r3b2-mark-forgotten-each-turn` (R3b-2's survivor-by-design) is re-run here: under the `last` reading a drop
# re-anchors the mark anyway, so forgetting it changed nothing; under the HIGH-WATER default it should be LIVE.
#
# ⛔ RESTORED FROM A COPY, NEVER FROM GIT — a harness that restores with `git checkout` restores over uncommitted
# work. The script refuses to start on a dirty tree.
#
# ⛔ DO NOT EDIT THIS FILE WHILE IT IS RUNNING. Bash reads a script incrementally, by byte offset.
#
#   bash tools/harness/mutants-r3c.sh <out-dir> [name-filter]
set -uo pipefail
cd "$(dirname "$0")/../.."
OUT="${1:?usage: mutants-r3c.sh <out-dir> [name-filter]}"
ONLY="${2:-}"
mkdir -p "$OUT"
if [ -n "$(git status --porcelain)" ]; then echo "REFUSING: the tree is dirty. Commit first — a mutant round restores over whatever is here."; exit 1; fi
AUTO=loader/tmt-auto.js
cp "$AUTO" "$OUT/tmt-auto.js.orig"
restore() { cp "$OUT/tmt-auto.js.orig" "$AUTO"; }
trap restore EXIT

mutant() {
  local name="$1" mut="$2"; shift 2
  if [ -n "$ONLY" ] && [[ "$name" != *"$ONLY"* ]]; then return 0; fi
  restore
  python3 -c "$mut" || { echo "$name: THE MUTATION DID NOT APPLY"; return 1; }
  echo "=== $name ==="
  git --no-pager diff --stat -- "$AUTO"
  "$@" > "$OUT/$name.log" 2>&1
  echo "$name: exit $? — $(grep -acE '^(RED|not ok)' "$OUT/$name.log") RED row(s), $(grep -acE '^(GREEN|ok )' "$OUT/$name.log") green"
  grep -aE '^(RED|not ok)' "$OUT/$name.log" | cut -c1-260
  restore
  git --no-pager diff --stat -- "$AUTO" | grep . && echo "!! NOT RESTORED" || echo "restored: diff is empty"
}

UNIT="node --test loader/cycle.test.mjs"
HIGH="      if (p - mark > need) { C.mark[f.id] = p; C.closer = now; } else if (before !== undefined && p < before) C.closer = now;"

# ⛔ THE HIGH-WATER READS AS THE LAST ANCHOR: a drop lowers the mark again. `high` becomes `last` and the leg that runs
# one re-climb under both readings sees them agree.
mutant m-r3c-high-reads-as-last \
  "p='$AUTO';s=open(p).read();o='''$HIGH''';assert o in s, 'anchor';s=s.replace(o,'''      if (p - mark > need || (before !== undefined && p < before)) { C.mark[f.id] = p; C.closer = now; }''');open(p,'w').write(s)" \
  $UNIT

# ⛔ A DROP NO LONGER RESTARTS THE CLOCK under the high-water — the live member (PTR's `h`, its Time Energy wiped by
# `t`'s own resets) is starved. `m-r3b2-wipe-costs-the-turn` one reading over.
mutant m-r3c-high-drop-keeps-the-clock \
  "p='$AUTO';s=open(p).read();o='''$HIGH''';assert o in s, 'anchor';s=s.replace(o,'''      if (p - mark > need) { C.mark[f.id] = p; C.closer = now; }''');open(p,'w').write(s)" \
  $UNIT

# ⛔ THE DEFECT THIS SLICE ACTUALLY WROTE AND ITS STUB LEG CAUGHT: "a drop" read as a reading BELOW THE MARK. Every
# tick of a re-climb then restarts the clock, nothing is ever released, and the freeze is back.
mutant m-r3c-drop-means-below-the-mark \
  "p='$AUTO';s=open(p).read();o='''$HIGH''';assert o in s, 'anchor';s=s.replace(o,'''      if (p - mark > need) { C.mark[f.id] = p; C.closer = now; } else if (p < mark) C.closer = now;''');open(p,'w').write(s)" \
  $UNIT

# ⛔ `high-act` WITHOUT ITS ACT: the clear on the member's own reset removed, so `high-act` is `high`.
mutant m-r3c-act-keeps-the-mark \
  "p='$AUTO';s=open(p).read();o=\"    if (turnMarkNow === 'high-act' && C.mark) { delete C.mark[f.id]; if (C.prev) delete C.prev[f.id]; }\";assert o in s, 'anchor';s=s.replace(o,'');open(p,'w').write(s)" \
  $UNIT

# ⛔ THE DEFAULT MOVED BACK: absent `turnMark` reads as `last`. The default leg compares absent against both readings.
# (In CI, `gates-r3c --part 1m`'s pinned default cell and `gates-c1 --part 4`'s re-recorded pin are two more guards.)
mutant m-r3c-default-is-last \
  "p='$AUTO';s=open(p).read();o=\"TURN_MARK_DEFAULT = 'high-act'\";assert o in s, 'anchor';s=s.replace(o,\"TURN_MARK_DEFAULT = 'last'\");open(p,'w').write(s)" \
  $UNIT

# ⚠ R3b-2's SURVIVOR, re-asked under the new default: the mark cleared at the start of every turn. Under `high-act` a
# dead member's re-climb then reads as progress again — the default leg should see the default behave as `last`.
mutant m-r3b2-mark-forgotten-each-turn \
  "p='$AUTO';s=open(p).read();o='    C.closer = C.since;';assert o in s, 'anchor';s=s.replace(o,'    C.closer = C.since; if (C.mark) delete C.mark[f.id];');open(p,'w').write(s)" \
  $UNIT
