#!/usr/bin/env bash
# F1's mutant round — the passive-generation yield, its off-switch, the derived default, and the maxRow repair.
#
# ⛔ FOR EVERY MUTANT, THE TWO QUESTIONS (V4's Part 5, kept): can it move its leg's OWN reference (the leg must build
# the thing it checks, not read it off the mutated build's history), and does a SECOND guard make it redundant?
#   · every stub leg in loader/passive.test.mjs builds its own control in the same test (a layer the game does not
#     pay, the same layer with the option off, a numeric maxRow) — a mutant cannot move both sides;
#   · `gates-f1 --part pin` compares against a LITERAL hash recorded before F1 existed, so no mutant can move it.
#
# ⛔ RESTORED FROM A COPY, NEVER FROM GIT — a harness that restores with `git checkout` restores over uncommitted
# work. The script refuses to start on a dirty tree.
# ⛔ DO NOT EDIT THIS FILE WHILE IT IS RUNNING. Bash reads a script incrementally, by byte offset.
#
#   bash tools/harness/mutants-f1.sh <out-dir> [name-filter]
set -uo pipefail
cd "$(dirname "$0")/../.."
OUT="${1:?usage: mutants-f1.sh <out-dir> [name-filter]}"
ONLY="${2:-}"
mkdir -p "$OUT"
if [ -n "$(git status --porcelain)" ]; then echo "REFUSING: the tree is dirty. Commit first — a mutant round restores over whatever is here."; exit 1; fi
AUTO=loader/tmt-auto.js
cp "$AUTO" "$OUT/tmt-auto.js.orig"
restore() { cp "$OUT/tmt-auto.js.orig" "$AUTO"; }
trap restore EXIT

mutant() {
  local name="$1" mut="$2"; shift 2
  if [ -n "$ONLY" ] && [[ "$name" != *"$ONLY"* ]]; then return 0; fi
  restore
  python3 -c "$mut" || { echo "$name: THE MUTATION DID NOT APPLY"; return 1; }
  echo "=== $name ==="
  git --no-pager diff --stat -- "$AUTO"
  local rc=0
  for cmd in "$@"; do bash -c "$cmd" >> "$OUT/$name.log" 2>&1 || rc=1; done
  echo "$name: exit $rc — $(grep -acE '^(RED|not ok)' "$OUT/$name.log") RED row(s), $(grep -acE '^(GREEN|ok )' "$OUT/$name.log") green"
  grep -aE '^(RED|not ok)' "$OUT/$name.log" | cut -c1-260
  restore
  git --no-pager diff --stat -- "$AUTO" | grep . && echo "!! NOT RESTORED" || echo "restored: diff is empty"
}
rep() { echo "p='$AUTO';s=open(p).read();o='''$1''';assert s.count(o)==1, 'anchor';s=s.replace(o,'''$2''');open(p,'w').write(s)"; }

UNIT="node --test loader/passive.test.mjs"
PIN="node tools/harness/gates-f1.mjs --part pin --no-write --assert"

# ⛔ the brief's three
mutant m-f1-yield-ignores-threshold "$(rep 'return r > passiveYieldNow ? r : null;' 'return r > 0 ? r : null;')" "$UNIT"
mutant m-f1-yield-fires-on-a-never-reset-layer "$(rep "    if (!player[l] || !player[l].unlocked) return null;
    var r = passiveRateOf(l);" "    var r = passiveRateOf(l);")" "$UNIT"
mutant m-f1-off-does-not-switch-off "$(rep "else if (String(py) === 'off') passiveYieldNow = null;" "else if (String(py) === 'off') passiveYieldNow = 0;")" "$UNIT" "$PIN"
# the other guards this slice added
mutant m-f1-yielding-member-stays-in-the-cycle "$(rep "if (g.kind !== 'reset' || !active(g) || passiveYieldOf(g.layer) !== null) continue;" "if (g.kind !== 'reset' || !active(g)) continue;")" "$UNIT"
mutant m-f1-yield-never-consulted "$(rep "    if (pr !== null) return { act: false, code: 'yielding:passive'" "    if (false) return { act: false, code: 'yielding:passive'")" "$UNIT"
mutant m-f1-default-back-to-gain2x "$(rep "var RESET_DEFAULT = 'gain>=2x|stall>=5x/5';" "var RESET_DEFAULT = 'gain>=2x';")" "node --test loader/strategies.test.mjs"
mutant m-f1-fallback-counts-every-reset "$(rep "      if (d.fallback) { stallFired.loop = loopNo; stallFired.layer = f.layer; T.fallbackFires[f.id] = (T.fallbackFires[f.id] || 0) + 1; }" "      T.fallbackFires[f.id] = (T.fallbackFires[f.id] || 0) + 1; if (d.fallback) { stallFired.loop = loopNo; stallFired.layer = f.layer; }")" "$UNIT"
mutant m-f1-maxrow-repair-never-runs "$(rep "  function auAutomate() {
    repairMaxRow();" "  function auAutomate() {")" "$UNIT"
mutant m-f1-maxrow-repair-numeric-max "$(rep "      if (m < dr) m = dr;" "      if (!isNaN(dr) && dr !== null && Number(dr) > Number(m)) m = Number(dr);")" "$UNIT"
