// docs/games.md — the roster, generated from manifests/ so it cannot drift from what the loader actually hosts.
//
// The table lived in README.md and was kept by hand. It is 40 rows today and the roster is meant to grow to the
// census top 100, at which point a hand-kept copy is both most of the README and certain to go stale — the
// manifests are the source of truth for every column in it.
//
//   node tools/games-table.mjs           rewrite docs/games.md
//   node tools/games-table.mjs --check   report without writing; exit 1 when it is out of date or inconsistent
//
// `checkGamesTable()` is the same check as a value, for gate G6 in gates.mjs.
import fs from 'node:fs';
import path from 'node:path';
import { REPO } from './harness/lib.mjs';

export const OUT = 'docs/games.md';
export const DECLINED = 'manifests/declined.json';
const LIVE = 'https://peerinfinity.github.io/tmt-loader/';
const esc = (s) => String(s).replace(/\|/g, '\\|');

/** The roster as the manifests declare it, in `manifests/index.json` order. */
export function rosterFromManifests() {
  const index = JSON.parse(fs.readFileSync(path.join(REPO, 'manifests/index.json'), 'utf8'));
  return index.map(({ id }) => {
    const m = JSON.parse(fs.readFileSync(path.join(REPO, `manifests/${id}.json`), 'utf8'));
    const up = m.upstream || {};
    return { id, name: m.name, repo: up.repo || '', commit: (up.commit || '').slice(0, 7),
      engine: (m.engine && m.engine.tmtNum) || '?', license: (m.license && m.license.verdict) || '?' };
  });
}

export function render(rows) {
  return [
    '# The games',
    '',
    `${rows.length} games, in the order they were added — the same order \`manifests/index.json\` and the loader's own`,
    'picker use. The first two were added by hand; the rest by `tools/add-game.mjs` from the',
    '[tmt-fork-census](https://github.com/PeerInfinity/tmt-fork-census) top 100, choosing games whose own play page',
    'no longer works.',
    '',
    'Each game lives under `games/<id>/` as a **git subtree**, pristine at the upstream commit its manifest records,',
    'and keeps its own license files and credits inside that subtree. `play` opens it on the published loader;',
    '`mobile` opens the same game in the [mobile layout](mobile.md).',
    '',
    '> Generated by `node tools/games-table.mjs` from `manifests/` — do not edit by hand.',
    '',
    '| id | game | play | upstream | engine | license |',
    '|---|---|---|---|---|---|',
    ...rows.map((r) => `| \`${r.id}\` | ${esc(r.name)} | [play](${LIVE}?mod=${encodeURIComponent(r.id)}) · [mobile](${LIVE}?mod=${encodeURIComponent(r.id)}&mobile=1) | \`${esc(r.repo)}\` @ \`${r.commit}\` | TMT ${esc(r.engine)} | ${esc(r.license)} |`),
    '',
  ].join('\n');
}

/** The ids the COMMITTED file lists, read back out of its table — not out of the generator. */
export function idsInDoc(text) {
  return [...text.matchAll(/^\| `([^`]+)` \| /gm)].map((m) => m[1]);
}

/**
 * Gate G6. Comparing the file to what the generator would emit proves only that the two AGREE — a generator that
 * dropped a game, run to regenerate the file, leaves them agreeing on the wrong roster. Measured: a one-character
 * mutant (`index.slice(0, -1)`) plus a regenerate was GREEN until this check read its roster separately.
 *
 * So the ids are compared against `manifests/index.json` read HERE, directly — not through `rosterFromManifests()`,
 * which is the generator's own path and would carry the same bug into both sides of the comparison. That file is
 * what the loader's picker enumerates, so it is the roster of record for the one claim this document makes: that
 * it lists every game the loader hosts, once, in that order.
 */
export function checkGamesTable() {
  const f = path.join(REPO, OUT);
  const rows = rosterFromManifests();
  const want = render(rows);
  const have = fs.existsSync(f) ? fs.readFileSync(f, 'utf8') : null;
  const problems = [];
  if (have === null) problems.push(`${OUT} does not exist`);
  else if (have !== want) problems.push(`${OUT} is out of date — run: node tools/games-table.mjs`);

  // read independently of rosterFromManifests(): see the note above
  const manifestIds = JSON.parse(fs.readFileSync(path.join(REPO, 'manifests/index.json'), 'utf8')).map((e) => e.id);
  if (rows.length !== manifestIds.length) problems.push(`the generator built ${rows.length} rows from ${manifestIds.length} manifests`);
  const docIds = have === null ? [] : idsInDoc(have);
  const missing = manifestIds.filter((i) => !docIds.includes(i));
  const extra = docIds.filter((i) => !manifestIds.includes(i));
  const dupes = [...new Set(docIds.filter((i, k) => docIds.indexOf(i) !== k))];
  if (missing.length) problems.push(`hosted but not listed: ${missing.join(', ')}`);
  if (extra.length) problems.push(`listed but not hosted: ${extra.join(', ')}`);
  if (dupes.length) problems.push(`listed twice: ${dupes.join(', ')}`);
  if (!missing.length && !extra.length && !dupes.length && docIds.join() !== manifestIds.join())
    problems.push('listed in a different order from manifests/index.json');

  return { ok: problems.length === 0, games: manifestIds.length, built: rows.length, listed: docIds.length, upToDate: have === want, problems };
}

/**
 * Gate G7. `manifests/declined.json` records the games this loader LOOKED AT and did not host, and why — the
 * judgement belongs on this side, where the attempt was made and the evidence is. The one thing that can rot is
 * the obvious one: a game gets fixed and added, and nobody removes its entry, so the list publishes a reason for
 * a game that is right there. (Five games were unblocked by one emitter fix in a single afternoon.) So: every
 * declined repo must NOT be hosted, every entry must carry a non-empty reason, and no repo may appear twice.
 */
export function checkDeclined() {
  const f = path.join(REPO, DECLINED);
  const problems = [];
  let list = [];
  try { list = JSON.parse(fs.readFileSync(f, 'utf8')); }
  catch (e) { return { ok: false, declined: 0, problems: [`${DECLINED}: ${e.message}`] }; }
  if (!Array.isArray(list)) return { ok: false, declined: 0, problems: [`${DECLINED} is not an array`] };

  const hosted = new Map();  // upstream repo (lower) -> id
  for (const { id } of JSON.parse(fs.readFileSync(path.join(REPO, 'manifests/index.json'), 'utf8'))) {
    const m = JSON.parse(fs.readFileSync(path.join(REPO, `manifests/${id}.json`), 'utf8'));
    const r = m.upstream && m.upstream.repo;
    if (r) hosted.set(r.toLowerCase(), id);
  }
  const seen = new Set();
  for (const e of list) {
    const r = e && typeof e.repo === 'string' ? e.repo : null;
    if (!r) { problems.push(`an entry has no repo: ${JSON.stringify(e).slice(0, 80)}`); continue; }
    if (!e.reason || !String(e.reason).trim()) problems.push(`${r}: no reason`);
    if (seen.has(r.toLowerCase())) problems.push(`${r}: listed twice`);
    seen.add(r.toLowerCase());
    if (hosted.has(r.toLowerCase())) problems.push(`${r}: declined AND hosted as \`${hosted.get(r.toLowerCase())}\` — remove the entry`);
  }
  return { ok: problems.length === 0, declined: list.length, problems };
}

if (import.meta.url === `file://${process.argv[1]}`) {
  if (process.argv.includes('--check')) {
    const r = checkGamesTable(), d = checkDeclined();
    for (const p of r.problems) console.error(`${OUT}: ${p}`);
    for (const p of d.problems) console.error(`${DECLINED}: ${p}`);
    if (r.ok && d.ok) console.log(`${OUT} up to date — ${r.games} games in manifests/index.json, ${r.listed} listed; ${DECLINED}: ${d.declined} declined, none hosted`);
    process.exit(r.ok && d.ok ? 0 : 1);
  }
  const rows = rosterFromManifests();
  fs.writeFileSync(path.join(REPO, OUT), render(rows));
  console.log(`${OUT}: ${rows.length} games`);
}
