// docs/games.md — the roster, generated from manifests/ so it cannot drift from what the loader actually hosts.
//
// The table lived in README.md and was kept by hand. It is 40 rows today and the roster is meant to grow to the
// census top 100, at which point a hand-kept copy is both most of the README and certain to go stale — the
// manifests are the source of truth for every column in it.
//
//   node tools/games-table.mjs           rewrite docs/games.md
//   node tools/games-table.mjs --check   exit 1 if it is out of date (prints the diff hint), write nothing
import fs from 'node:fs';
import path from 'node:path';
import { REPO } from './harness/lib.mjs';

const OUT = path.join(REPO, 'docs/games.md');
const LIVE = 'https://peerinfinity.github.io/tmt-loader/';

const index = JSON.parse(fs.readFileSync(path.join(REPO, 'manifests/index.json'), 'utf8'));
const rows = index.map(({ id }) => {
  const m = JSON.parse(fs.readFileSync(path.join(REPO, `manifests/${id}.json`), 'utf8'));
  const up = m.upstream || {};
  return { id, name: m.name, repo: up.repo || '', commit: (up.commit || '').slice(0, 7),
    engine: (m.engine && m.engine.tmtNum) || '?', license: (m.license && m.license.verdict) || '?' };
});

const esc = (s) => String(s).replace(/\|/g, '\\|');
const body = [
  '# The games',
  '',
  `${rows.length} games, in the order they were added — the same order \`manifests/index.json\` and the loader's own`,
  'picker use. The first two were added by hand; the rest by `tools/add-game.mjs` from the',
  '[tmt-fork-census](https://github.com/PeerInfinity/tmt-fork-census) top 100, choosing games whose own play page',
  'no longer works.',
  '',
  'Each game lives under `games/<id>/` as a **git subtree**, pristine at the upstream commit its manifest records,',
  'and keeps its own license files and credits inside that subtree. `play` opens it on the published loader;',
  '`mobile` opens the same game in the [mobile layout](mobile.md).',
  '',
  '> Generated by `node tools/games-table.mjs` from `manifests/` — do not edit by hand.',
  '',
  '| id | game | play | upstream | engine | license |',
  '|---|---|---|---|---|---|',
  ...rows.map((r) => `| \`${r.id}\` | ${esc(r.name)} | [play](${LIVE}?mod=${encodeURIComponent(r.id)}) · [mobile](${LIVE}?mod=${encodeURIComponent(r.id)}&mobile=1) | \`${esc(r.repo)}\` @ \`${r.commit}\` | TMT ${esc(r.engine)} | ${esc(r.license)} |`),
  '',
].join('\n');

if (process.argv.includes('--check')) {
  const cur = fs.existsSync(OUT) ? fs.readFileSync(OUT, 'utf8') : '';
  if (cur === body) { console.log(`docs/games.md up to date (${rows.length} games)`); process.exit(0); }
  console.error(`docs/games.md is out of date (${rows.length} games in manifests/) — run: node tools/games-table.mjs`);
  process.exit(1);
}
fs.writeFileSync(OUT, body);
console.log(`docs/games.md: ${rows.length} games`);
